/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as IngredientsIndexRouteImport } from './routes/ingredients/index'
import { Route as ImportIndexRouteImport } from './routes/import/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as ArchiveIndexRouteImport } from './routes/archive/index'
import { Route as TemplatesNewRouteImport } from './routes/templates/new'
import { Route as IngredientsNewRouteImport } from './routes/ingredients/new'
import { Route as ComponentsNewRouteImport } from './routes/components/new'
import { Route as ArchiveIdIndexRouteImport } from './routes/archive/$id/index'
import { Route as IngredientsIdEditRouteImport } from './routes/ingredients/$id/edit'
import { Route as ComponentsIdEditRouteImport } from './routes/components/$id/edit'
import { Route as PlannerWeekIdDaySlotIdPickRouteImport } from './routes/planner/$weekId/$day/$slotId/pick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIndexRoute = IngredientsIndexRouteImport.update({
  id: '/ingredients/',
  path: '/ingredients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportIndexRoute = ImportIndexRouteImport.update({
  id: '/import/',
  path: '/import/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIndexRoute = ArchiveIndexRouteImport.update({
  id: '/archive/',
  path: '/archive/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesNewRoute = TemplatesNewRouteImport.update({
  id: '/templates/new',
  path: '/templates/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsNewRoute = IngredientsNewRouteImport.update({
  id: '/ingredients/new',
  path: '/ingredients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsNewRoute = ComponentsNewRouteImport.update({
  id: '/components/new',
  path: '/components/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIdIndexRoute = ArchiveIdIndexRouteImport.update({
  id: '/archive/$id/',
  path: '/archive/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIdEditRoute = IngredientsIdEditRouteImport.update({
  id: '/ingredients/$id/edit',
  path: '/ingredients/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIdEditRoute = ComponentsIdEditRouteImport.update({
  id: '/components/$id/edit',
  path: '/components/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerWeekIdDaySlotIdPickRoute =
  PlannerWeekIdDaySlotIdPickRouteImport.update({
    id: '/planner/$weekId/$day/$slotId/pick',
    path: '/planner/$weekId/$day/$slotId/pick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/new': typeof ComponentsNewRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/templates/new': typeof TemplatesNewRoute
  '/archive/': typeof ArchiveIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/import/': typeof ImportIndexRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/components/$id/edit': typeof ComponentsIdEditRoute
  '/ingredients/$id/edit': typeof IngredientsIdEditRoute
  '/archive/$id/': typeof ArchiveIdIndexRoute
  '/planner/$weekId/$day/$slotId/pick': typeof PlannerWeekIdDaySlotIdPickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/new': typeof ComponentsNewRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/templates/new': typeof TemplatesNewRoute
  '/archive': typeof ArchiveIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/import': typeof ImportIndexRoute
  '/ingredients': typeof IngredientsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/components/$id/edit': typeof ComponentsIdEditRoute
  '/ingredients/$id/edit': typeof IngredientsIdEditRoute
  '/archive/$id': typeof ArchiveIdIndexRoute
  '/planner/$weekId/$day/$slotId/pick': typeof PlannerWeekIdDaySlotIdPickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components/new': typeof ComponentsNewRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/templates/new': typeof TemplatesNewRoute
  '/archive/': typeof ArchiveIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/import/': typeof ImportIndexRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/components/$id/edit': typeof ComponentsIdEditRoute
  '/ingredients/$id/edit': typeof IngredientsIdEditRoute
  '/archive/$id/': typeof ArchiveIdIndexRoute
  '/planner/$weekId/$day/$slotId/pick': typeof PlannerWeekIdDaySlotIdPickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components/new'
    | '/ingredients/new'
    | '/templates/new'
    | '/archive/'
    | '/components/'
    | '/import/'
    | '/ingredients/'
    | '/settings/'
    | '/templates/'
    | '/components/$id/edit'
    | '/ingredients/$id/edit'
    | '/archive/$id/'
    | '/planner/$weekId/$day/$slotId/pick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/new'
    | '/ingredients/new'
    | '/templates/new'
    | '/archive'
    | '/components'
    | '/import'
    | '/ingredients'
    | '/settings'
    | '/templates'
    | '/components/$id/edit'
    | '/ingredients/$id/edit'
    | '/archive/$id'
    | '/planner/$weekId/$day/$slotId/pick'
  id:
    | '__root__'
    | '/'
    | '/components/new'
    | '/ingredients/new'
    | '/templates/new'
    | '/archive/'
    | '/components/'
    | '/import/'
    | '/ingredients/'
    | '/settings/'
    | '/templates/'
    | '/components/$id/edit'
    | '/ingredients/$id/edit'
    | '/archive/$id/'
    | '/planner/$weekId/$day/$slotId/pick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsNewRoute: typeof ComponentsNewRoute
  IngredientsNewRoute: typeof IngredientsNewRoute
  TemplatesNewRoute: typeof TemplatesNewRoute
  ArchiveIndexRoute: typeof ArchiveIndexRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  ImportIndexRoute: typeof ImportIndexRoute
  IngredientsIndexRoute: typeof IngredientsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  ComponentsIdEditRoute: typeof ComponentsIdEditRoute
  IngredientsIdEditRoute: typeof IngredientsIdEditRoute
  ArchiveIdIndexRoute: typeof ArchiveIdIndexRoute
  PlannerWeekIdDaySlotIdPickRoute: typeof PlannerWeekIdDaySlotIdPickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/': {
      id: '/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof IngredientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import/': {
      id: '/import/'
      path: '/import'
      fullPath: '/import/'
      preLoaderRoute: typeof ImportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/': {
      id: '/archive/'
      path: '/archive'
      fullPath: '/archive/'
      preLoaderRoute: typeof ArchiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/new': {
      id: '/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof TemplatesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/new': {
      id: '/ingredients/new'
      path: '/ingredients/new'
      fullPath: '/ingredients/new'
      preLoaderRoute: typeof IngredientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/new': {
      id: '/components/new'
      path: '/components/new'
      fullPath: '/components/new'
      preLoaderRoute: typeof ComponentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$id/': {
      id: '/archive/$id/'
      path: '/archive/$id'
      fullPath: '/archive/$id/'
      preLoaderRoute: typeof ArchiveIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/$id/edit': {
      id: '/ingredients/$id/edit'
      path: '/ingredients/$id/edit'
      fullPath: '/ingredients/$id/edit'
      preLoaderRoute: typeof IngredientsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$id/edit': {
      id: '/components/$id/edit'
      path: '/components/$id/edit'
      fullPath: '/components/$id/edit'
      preLoaderRoute: typeof ComponentsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner/$weekId/$day/$slotId/pick': {
      id: '/planner/$weekId/$day/$slotId/pick'
      path: '/planner/$weekId/$day/$slotId/pick'
      fullPath: '/planner/$weekId/$day/$slotId/pick'
      preLoaderRoute: typeof PlannerWeekIdDaySlotIdPickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsNewRoute: ComponentsNewRoute,
  IngredientsNewRoute: IngredientsNewRoute,
  TemplatesNewRoute: TemplatesNewRoute,
  ArchiveIndexRoute: ArchiveIndexRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  ImportIndexRoute: ImportIndexRoute,
  IngredientsIndexRoute: IngredientsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  ComponentsIdEditRoute: ComponentsIdEditRoute,
  IngredientsIdEditRoute: IngredientsIdEditRoute,
  ArchiveIdIndexRoute: ArchiveIdIndexRoute,
  PlannerWeekIdDaySlotIdPickRoute: PlannerWeekIdDaySlotIdPickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
