// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const appendMessage = `-- name: AppendMessage :one
INSERT INTO ai_messages (conversation_id, role, content)
VALUES (?, ?, ?)
RETURNING id, conversation_id, role, content, created_at
`

type AppendMessageParams struct {
	ConversationID int64
	Role           string
	Content        string
}

func (q *Queries) AppendMessage(ctx context.Context, arg AppendMessageParams) (AiMessage, error) {
	row := q.db.QueryRowContext(ctx, appendMessage, arg.ConversationID, arg.Role, arg.Content)
	var i AiMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const countConversations = `-- name: CountConversations :one
SELECT COUNT(*) FROM ai_conversations
`

func (q *Queries) CountConversations(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConversations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countConversationsByWeek = `-- name: CountConversationsByWeek :one
SELECT COUNT(*) FROM ai_conversations WHERE week_id = ?
`

func (q *Queries) CountConversationsByWeek(ctx context.Context, weekID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConversationsByWeek, weekID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO ai_conversations (week_id, title)
VALUES (?, ?)
RETURNING id, week_id, title, created_at, updated_at
`

type CreateConversationParams struct {
	WeekID sql.NullInt64
	Title  sql.NullString
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (AiConversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation, arg.WeekID, arg.Title)
	var i AiConversation
	err := row.Scan(
		&i.ID,
		&i.WeekID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :execresult
DELETE FROM ai_conversations WHERE id = ?
`

func (q *Queries) DeleteConversation(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteConversation, id)
}

const getConversation = `-- name: GetConversation :one
SELECT id, week_id, title, created_at, updated_at FROM ai_conversations WHERE id = ?
`

func (q *Queries) GetConversation(ctx context.Context, id int64) (AiConversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, id)
	var i AiConversation
	err := row.Scan(
		&i.ID,
		&i.WeekID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT id, week_id, title, created_at, updated_at FROM ai_conversations
ORDER BY updated_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListConversationsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]AiConversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiConversation{}
	for rows.Next() {
		var i AiConversation
		if err := rows.Scan(
			&i.ID,
			&i.WeekID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsByWeek = `-- name: ListConversationsByWeek :many
SELECT id, week_id, title, created_at, updated_at FROM ai_conversations
WHERE week_id = ?
ORDER BY updated_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListConversationsByWeekParams struct {
	WeekID sql.NullInt64
	Limit  int64
	Offset int64
}

func (q *Queries) ListConversationsByWeek(ctx context.Context, arg ListConversationsByWeekParams) ([]AiConversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversationsByWeek, arg.WeekID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiConversation{}
	for rows.Next() {
		var i AiConversation
		if err := rows.Scan(
			&i.ID,
			&i.WeekID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, role, content, created_at FROM ai_messages
WHERE conversation_id = ?
ORDER BY id ASC
`

func (q *Queries) ListMessages(ctx context.Context, conversationID int64) ([]AiMessage, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiMessage{}
	for rows.Next() {
		var i AiMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchConversation = `-- name: TouchConversation :execresult
UPDATE ai_conversations SET updated_at = datetime('now') WHERE id = ?
`

func (q *Queries) TouchConversation(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, touchConversation, id)
}

const updateConversationTitle = `-- name: UpdateConversationTitle :one
UPDATE ai_conversations
SET title = ?, updated_at = datetime('now')
WHERE id = ?
RETURNING id, week_id, title, created_at, updated_at
`

type UpdateConversationTitleParams struct {
	Title sql.NullString
	ID    int64
}

func (q *Queries) UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) (AiConversation, error) {
	row := q.db.QueryRowContext(ctx, updateConversationTitle, arg.Title, arg.ID)
	var i AiConversation
	err := row.Scan(
		&i.ID,
		&i.WeekID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
