// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_settings.sql

package sqlcgen

import (
	"context"
)

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM app_settings WHERE key = ?
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteSetting, key)
	return err
}

const getSetting = `-- name: GetSetting :one
SELECT key, value, encrypted, updated_at
FROM app_settings
WHERE key = ?
`

func (q *Queries) GetSetting(ctx context.Context, key string) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var i AppSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Encrypted,
		&i.UpdatedAt,
	)
	return i, err
}

const listSettings = `-- name: ListSettings :many
SELECT key, value, encrypted, updated_at
FROM app_settings
ORDER BY key
`

func (q *Queries) ListSettings(ctx context.Context) ([]AppSetting, error) {
	rows, err := q.db.QueryContext(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSetting{}
	for rows.Next() {
		var i AppSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Encrypted,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO app_settings (key, value, encrypted, updated_at)
VALUES (?, ?, ?, datetime('now'))
ON CONFLICT(key) DO UPDATE SET
    value      = excluded.value,
    encrypted  = excluded.encrypted,
    updated_at = datetime('now')
`

type UpsertSettingParams struct {
	Key       string
	Value     string
	Encrypted int64
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.Value, arg.Encrypted)
	return err
}
