// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: components.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createComponent = `-- name: CreateComponent :one
INSERT INTO components (name, role, variant_group_id, reference_portions, prep_minutes, cook_minutes, image_path, notes)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, role, variant_group_id, reference_portions, prep_minutes, cook_minutes, image_path, notes, last_cooked_at, cook_count, created_at, updated_at
`

type CreateComponentParams struct {
	Name              string
	Role              string
	VariantGroupID    sql.NullInt64
	ReferencePortions float64
	PrepMinutes       sql.NullInt64
	CookMinutes       sql.NullInt64
	ImagePath         sql.NullString
	Notes             sql.NullString
}

func (q *Queries) CreateComponent(ctx context.Context, arg CreateComponentParams) (Component, error) {
	row := q.db.QueryRowContext(ctx, createComponent,
		arg.Name,
		arg.Role,
		arg.VariantGroupID,
		arg.ReferencePortions,
		arg.PrepMinutes,
		arg.CookMinutes,
		arg.ImagePath,
		arg.Notes,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.VariantGroupID,
		&i.ReferencePortions,
		&i.PrepMinutes,
		&i.CookMinutes,
		&i.ImagePath,
		&i.Notes,
		&i.LastCookedAt,
		&i.CookCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createComponentIngredient = `-- name: CreateComponentIngredient :exec
INSERT INTO component_ingredients (component_id, ingredient_id, amount, unit, grams, sort_order)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateComponentIngredientParams struct {
	ComponentID  int64
	IngredientID int64
	Amount       float64
	Unit         string
	Grams        float64
	SortOrder    int64
}

func (q *Queries) CreateComponentIngredient(ctx context.Context, arg CreateComponentIngredientParams) error {
	_, err := q.db.ExecContext(ctx, createComponentIngredient,
		arg.ComponentID,
		arg.IngredientID,
		arg.Amount,
		arg.Unit,
		arg.Grams,
		arg.SortOrder,
	)
	return err
}

const createComponentInstruction = `-- name: CreateComponentInstruction :exec
INSERT INTO component_instructions (component_id, step_number, text)
VALUES (?, ?, ?)
`

type CreateComponentInstructionParams struct {
	ComponentID int64
	StepNumber  int64
	Text        string
}

func (q *Queries) CreateComponentInstruction(ctx context.Context, arg CreateComponentInstructionParams) error {
	_, err := q.db.ExecContext(ctx, createComponentInstruction, arg.ComponentID, arg.StepNumber, arg.Text)
	return err
}

const createComponentTag = `-- name: CreateComponentTag :exec
INSERT INTO component_tags (component_id, tag) VALUES (?, ?)
`

type CreateComponentTagParams struct {
	ComponentID int64
	Tag         string
}

func (q *Queries) CreateComponentTag(ctx context.Context, arg CreateComponentTagParams) error {
	_, err := q.db.ExecContext(ctx, createComponentTag, arg.ComponentID, arg.Tag)
	return err
}

const createVariantGroup = `-- name: CreateVariantGroup :one
INSERT INTO variant_groups (name) VALUES (?) RETURNING id, name, created_at
`

func (q *Queries) CreateVariantGroup(ctx context.Context, name string) (VariantGroup, error) {
	row := q.db.QueryRowContext(ctx, createVariantGroup, name)
	var i VariantGroup
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteComponent = `-- name: DeleteComponent :execresult
DELETE FROM components WHERE id = ?
`

func (q *Queries) DeleteComponent(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteComponent, id)
}

const deleteComponentIngredients = `-- name: DeleteComponentIngredients :exec
DELETE FROM component_ingredients WHERE component_id = ?
`

func (q *Queries) DeleteComponentIngredients(ctx context.Context, componentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteComponentIngredients, componentID)
	return err
}

const deleteComponentInstructions = `-- name: DeleteComponentInstructions :exec
DELETE FROM component_instructions WHERE component_id = ?
`

func (q *Queries) DeleteComponentInstructions(ctx context.Context, componentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteComponentInstructions, componentID)
	return err
}

const deleteComponentTags = `-- name: DeleteComponentTags :exec
DELETE FROM component_tags WHERE component_id = ?
`

func (q *Queries) DeleteComponentTags(ctx context.Context, componentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteComponentTags, componentID)
	return err
}

const getComponent = `-- name: GetComponent :one
SELECT id, name, role, variant_group_id, reference_portions, prep_minutes, cook_minutes, image_path, notes, last_cooked_at, cook_count, created_at, updated_at FROM components WHERE id = ?
`

func (q *Queries) GetComponent(ctx context.Context, id int64) (Component, error) {
	row := q.db.QueryRowContext(ctx, getComponent, id)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.VariantGroupID,
		&i.ReferencePortions,
		&i.PrepMinutes,
		&i.CookMinutes,
		&i.ImagePath,
		&i.Notes,
		&i.LastCookedAt,
		&i.CookCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listComponentIngredients = `-- name: ListComponentIngredients :many
SELECT id, component_id, ingredient_id, amount, unit, grams, sort_order FROM component_ingredients WHERE component_id = ? ORDER BY sort_order
`

func (q *Queries) ListComponentIngredients(ctx context.Context, componentID int64) ([]ComponentIngredient, error) {
	rows, err := q.db.QueryContext(ctx, listComponentIngredients, componentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComponentIngredient{}
	for rows.Next() {
		var i ComponentIngredient
		if err := rows.Scan(
			&i.ID,
			&i.ComponentID,
			&i.IngredientID,
			&i.Amount,
			&i.Unit,
			&i.Grams,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponentInstructions = `-- name: ListComponentInstructions :many
SELECT id, component_id, step_number, text FROM component_instructions WHERE component_id = ? ORDER BY step_number
`

func (q *Queries) ListComponentInstructions(ctx context.Context, componentID int64) ([]ComponentInstruction, error) {
	rows, err := q.db.QueryContext(ctx, listComponentInstructions, componentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComponentInstruction{}
	for rows.Next() {
		var i ComponentInstruction
		if err := rows.Scan(
			&i.ID,
			&i.ComponentID,
			&i.StepNumber,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponentTags = `-- name: ListComponentTags :many
SELECT component_id, tag FROM component_tags WHERE component_id = ? ORDER BY tag
`

func (q *Queries) ListComponentTags(ctx context.Context, componentID int64) ([]ComponentTag, error) {
	rows, err := q.db.QueryContext(ctx, listComponentTags, componentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComponentTag{}
	for rows.Next() {
		var i ComponentTag
		if err := rows.Scan(&i.ComponentID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiblingComponents = `-- name: ListSiblingComponents :many
SELECT id, name, role, variant_group_id, reference_portions, prep_minutes, cook_minutes, image_path, notes, last_cooked_at, cook_count, created_at, updated_at FROM components WHERE variant_group_id = ? AND id != ? ORDER BY name
`

type ListSiblingComponentsParams struct {
	VariantGroupID sql.NullInt64
	ID             int64
}

func (q *Queries) ListSiblingComponents(ctx context.Context, arg ListSiblingComponentsParams) ([]Component, error) {
	rows, err := q.db.QueryContext(ctx, listSiblingComponents, arg.VariantGroupID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Component{}
	for rows.Next() {
		var i Component
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.VariantGroupID,
			&i.ReferencePortions,
			&i.PrepMinutes,
			&i.CookMinutes,
			&i.ImagePath,
			&i.Notes,
			&i.LastCookedAt,
			&i.CookCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markComponentCooked = `-- name: MarkComponentCooked :exec
UPDATE components
SET last_cooked_at = ?,
    cook_count     = cook_count + 1,
    updated_at     = datetime('now')
WHERE id = ?
`

type MarkComponentCookedParams struct {
	LastCookedAt sql.NullString
	ID           int64
}

func (q *Queries) MarkComponentCooked(ctx context.Context, arg MarkComponentCookedParams) error {
	_, err := q.db.ExecContext(ctx, markComponentCooked, arg.LastCookedAt, arg.ID)
	return err
}

const updateComponent = `-- name: UpdateComponent :one
UPDATE components SET
    name = ?,
    role = ?,
    variant_group_id = ?,
    reference_portions = ?,
    prep_minutes = ?,
    cook_minutes = ?,
    image_path = ?,
    notes = ?,
    updated_at = datetime('now')
WHERE id = ?
RETURNING id, name, role, variant_group_id, reference_portions, prep_minutes, cook_minutes, image_path, notes, last_cooked_at, cook_count, created_at, updated_at
`

type UpdateComponentParams struct {
	Name              string
	Role              string
	VariantGroupID    sql.NullInt64
	ReferencePortions float64
	PrepMinutes       sql.NullInt64
	CookMinutes       sql.NullInt64
	ImagePath         sql.NullString
	Notes             sql.NullString
	ID                int64
}

func (q *Queries) UpdateComponent(ctx context.Context, arg UpdateComponentParams) (Component, error) {
	row := q.db.QueryRowContext(ctx, updateComponent,
		arg.Name,
		arg.Role,
		arg.VariantGroupID,
		arg.ReferencePortions,
		arg.PrepMinutes,
		arg.CookMinutes,
		arg.ImagePath,
		arg.Notes,
		arg.ID,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.VariantGroupID,
		&i.ReferencePortions,
		&i.PrepMinutes,
		&i.CookMinutes,
		&i.ImagePath,
		&i.Notes,
		&i.LastCookedAt,
		&i.CookCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
