// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feedback.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deletePlateFeedback = `-- name: DeletePlateFeedback :execresult
DELETE FROM plate_feedback WHERE plate_id = ?
`

func (q *Queries) DeletePlateFeedback(ctx context.Context, plateID int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePlateFeedback, plateID)
}

const getPlateFeedback = `-- name: GetPlateFeedback :one
SELECT plate_id, status, note, rated_at FROM plate_feedback WHERE plate_id = ?
`

func (q *Queries) GetPlateFeedback(ctx context.Context, plateID int64) (PlateFeedback, error) {
	row := q.db.QueryRowContext(ctx, getPlateFeedback, plateID)
	var i PlateFeedback
	err := row.Scan(
		&i.PlateID,
		&i.Status,
		&i.Note,
		&i.RatedAt,
	)
	return i, err
}

const listPlateFeedbackByWeek = `-- name: ListPlateFeedbackByWeek :many
SELECT pf.plate_id, pf.status, pf.note, pf.rated_at
FROM plate_feedback pf
JOIN plates p ON p.id = pf.plate_id
WHERE p.week_id = ?
`

func (q *Queries) ListPlateFeedbackByWeek(ctx context.Context, weekID int64) ([]PlateFeedback, error) {
	rows, err := q.db.QueryContext(ctx, listPlateFeedbackByWeek, weekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlateFeedback{}
	for rows.Next() {
		var i PlateFeedback
		if err := rows.Scan(
			&i.PlateID,
			&i.Status,
			&i.Note,
			&i.RatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlateFeedback = `-- name: UpsertPlateFeedback :one
INSERT INTO plate_feedback (plate_id, status, note, rated_at)
VALUES (?, ?, ?, datetime('now'))
ON CONFLICT(plate_id) DO UPDATE SET
    status   = excluded.status,
    note     = excluded.note,
    rated_at = excluded.rated_at
RETURNING plate_id, status, note, rated_at
`

type UpsertPlateFeedbackParams struct {
	PlateID int64
	Status  string
	Note    sql.NullString
}

func (q *Queries) UpsertPlateFeedback(ctx context.Context, arg UpsertPlateFeedbackParams) (PlateFeedback, error) {
	row := q.db.QueryRowContext(ctx, upsertPlateFeedback, arg.PlateID, arg.Status, arg.Note)
	var i PlateFeedback
	err := row.Scan(
		&i.PlateID,
		&i.Status,
		&i.Note,
		&i.RatedAt,
	)
	return i, err
}
