// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: foods.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createFood = `-- name: CreateFood :one
INSERT INTO foods (
    name, kind, role, source, barcode, off_id, fdc_id, image_path,
    kcal_100g, protein_100g, fat_100g, carbs_100g, fiber_100g, sodium_100g,
    saturated_fat_100g, trans_fat_100g, cholesterol_100g, sugar_100g,
    potassium_100g, calcium_100g, iron_100g, magnesium_100g, phosphorus_100g, zinc_100g,
    vitamin_a_100g, vitamin_c_100g, vitamin_d_100g, vitamin_b12_100g, vitamin_b6_100g, folate_100g,
    variant_group_id, reference_portions, prep_minutes, cook_minutes, notes,
    favorite
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?
)
RETURNING id, name, kind, role, source, barcode, off_id, fdc_id, kcal_100g, protein_100g, fat_100g, carbs_100g, fiber_100g, sodium_100g, saturated_fat_100g, trans_fat_100g, cholesterol_100g, sugar_100g, potassium_100g, calcium_100g, iron_100g, magnesium_100g, phosphorus_100g, zinc_100g, vitamin_a_100g, vitamin_c_100g, vitamin_d_100g, vitamin_b12_100g, vitamin_b6_100g, folate_100g, variant_group_id, reference_portions, prep_minutes, cook_minutes, notes, image_path, favorite, last_cooked_at, cook_count, created_at, updated_at
`

type CreateFoodParams struct {
	Name              string
	Kind              string
	Role              sql.NullString
	Source            sql.NullString
	Barcode           sql.NullString
	OffID             sql.NullString
	FdcID             sql.NullString
	ImagePath         sql.NullString
	Kcal100g          sql.NullFloat64
	Protein100g       sql.NullFloat64
	Fat100g           sql.NullFloat64
	Carbs100g         sql.NullFloat64
	Fiber100g         sql.NullFloat64
	Sodium100g        sql.NullFloat64
	SaturatedFat100g  sql.NullFloat64
	TransFat100g      sql.NullFloat64
	Cholesterol100g   sql.NullFloat64
	Sugar100g         sql.NullFloat64
	Potassium100g     sql.NullFloat64
	Calcium100g       sql.NullFloat64
	Iron100g          sql.NullFloat64
	Magnesium100g     sql.NullFloat64
	Phosphorus100g    sql.NullFloat64
	Zinc100g          sql.NullFloat64
	VitaminA100g      sql.NullFloat64
	VitaminC100g      sql.NullFloat64
	VitaminD100g      sql.NullFloat64
	VitaminB12100g    sql.NullFloat64
	VitaminB6100g     sql.NullFloat64
	Folate100g        sql.NullFloat64
	VariantGroupID    sql.NullInt64
	ReferencePortions sql.NullFloat64
	PrepMinutes       sql.NullInt64
	CookMinutes       sql.NullInt64
	Notes             sql.NullString
	Favorite          int64
}

func (q *Queries) CreateFood(ctx context.Context, arg CreateFoodParams) (Food, error) {
	row := q.db.QueryRowContext(ctx, createFood,
		arg.Name,
		arg.Kind,
		arg.Role,
		arg.Source,
		arg.Barcode,
		arg.OffID,
		arg.FdcID,
		arg.ImagePath,
		arg.Kcal100g,
		arg.Protein100g,
		arg.Fat100g,
		arg.Carbs100g,
		arg.Fiber100g,
		arg.Sodium100g,
		arg.SaturatedFat100g,
		arg.TransFat100g,
		arg.Cholesterol100g,
		arg.Sugar100g,
		arg.Potassium100g,
		arg.Calcium100g,
		arg.Iron100g,
		arg.Magnesium100g,
		arg.Phosphorus100g,
		arg.Zinc100g,
		arg.VitaminA100g,
		arg.VitaminC100g,
		arg.VitaminD100g,
		arg.VitaminB12100g,
		arg.VitaminB6100g,
		arg.Folate100g,
		arg.VariantGroupID,
		arg.ReferencePortions,
		arg.PrepMinutes,
		arg.CookMinutes,
		arg.Notes,
		arg.Favorite,
	)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Role,
		&i.Source,
		&i.Barcode,
		&i.OffID,
		&i.FdcID,
		&i.Kcal100g,
		&i.Protein100g,
		&i.Fat100g,
		&i.Carbs100g,
		&i.Fiber100g,
		&i.Sodium100g,
		&i.SaturatedFat100g,
		&i.TransFat100g,
		&i.Cholesterol100g,
		&i.Sugar100g,
		&i.Potassium100g,
		&i.Calcium100g,
		&i.Iron100g,
		&i.Magnesium100g,
		&i.Phosphorus100g,
		&i.Zinc100g,
		&i.VitaminA100g,
		&i.VitaminC100g,
		&i.VitaminD100g,
		&i.VitaminB12100g,
		&i.VitaminB6100g,
		&i.Folate100g,
		&i.VariantGroupID,
		&i.ReferencePortions,
		&i.PrepMinutes,
		&i.CookMinutes,
		&i.Notes,
		&i.ImagePath,
		&i.Favorite,
		&i.LastCookedAt,
		&i.CookCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFoodComponent = `-- name: CreateFoodComponent :exec
INSERT INTO food_components (parent_id, child_id, amount, unit, grams, sort_order)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateFoodComponentParams struct {
	ParentID  int64
	ChildID   int64
	Amount    float64
	Unit      string
	Grams     float64
	SortOrder int64
}

func (q *Queries) CreateFoodComponent(ctx context.Context, arg CreateFoodComponentParams) error {
	_, err := q.db.ExecContext(ctx, createFoodComponent,
		arg.ParentID,
		arg.ChildID,
		arg.Amount,
		arg.Unit,
		arg.Grams,
		arg.SortOrder,
	)
	return err
}

const createFoodInstruction = `-- name: CreateFoodInstruction :exec
INSERT INTO food_instructions (food_id, step_number, text)
VALUES (?, ?, ?)
`

type CreateFoodInstructionParams struct {
	FoodID     int64
	StepNumber int64
	Text       string
}

func (q *Queries) CreateFoodInstruction(ctx context.Context, arg CreateFoodInstructionParams) error {
	_, err := q.db.ExecContext(ctx, createFoodInstruction, arg.FoodID, arg.StepNumber, arg.Text)
	return err
}

const createFoodTag = `-- name: CreateFoodTag :exec
INSERT INTO food_tags (food_id, tag) VALUES (?, ?)
`

type CreateFoodTagParams struct {
	FoodID int64
	Tag    string
}

func (q *Queries) CreateFoodTag(ctx context.Context, arg CreateFoodTagParams) error {
	_, err := q.db.ExecContext(ctx, createFoodTag, arg.FoodID, arg.Tag)
	return err
}

const createVariantGroup = `-- name: CreateVariantGroup :one
INSERT INTO variant_groups (name) VALUES (?) RETURNING id, name, created_at
`

func (q *Queries) CreateVariantGroup(ctx context.Context, name string) (VariantGroup, error) {
	row := q.db.QueryRowContext(ctx, createVariantGroup, name)
	var i VariantGroup
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteFood = `-- name: DeleteFood :execresult
DELETE FROM foods WHERE id = ?
`

func (q *Queries) DeleteFood(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteFood, id)
}

const deleteFoodComponents = `-- name: DeleteFoodComponents :exec
DELETE FROM food_components WHERE parent_id = ?
`

func (q *Queries) DeleteFoodComponents(ctx context.Context, parentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteFoodComponents, parentID)
	return err
}

const deleteFoodInstructions = `-- name: DeleteFoodInstructions :exec
DELETE FROM food_instructions WHERE food_id = ?
`

func (q *Queries) DeleteFoodInstructions(ctx context.Context, foodID int64) error {
	_, err := q.db.ExecContext(ctx, deleteFoodInstructions, foodID)
	return err
}

const deleteFoodPortion = `-- name: DeleteFoodPortion :execresult
DELETE FROM food_portions WHERE food_id = ? AND unit = ?
`

type DeleteFoodPortionParams struct {
	FoodID int64
	Unit   string
}

func (q *Queries) DeleteFoodPortion(ctx context.Context, arg DeleteFoodPortionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteFoodPortion, arg.FoodID, arg.Unit)
}

const deleteFoodTags = `-- name: DeleteFoodTags :exec
DELETE FROM food_tags WHERE food_id = ?
`

func (q *Queries) DeleteFoodTags(ctx context.Context, foodID int64) error {
	_, err := q.db.ExecContext(ctx, deleteFoodTags, foodID)
	return err
}

const getFood = `-- name: GetFood :one
SELECT id, name, kind, role, source, barcode, off_id, fdc_id, kcal_100g, protein_100g, fat_100g, carbs_100g, fiber_100g, sodium_100g, saturated_fat_100g, trans_fat_100g, cholesterol_100g, sugar_100g, potassium_100g, calcium_100g, iron_100g, magnesium_100g, phosphorus_100g, zinc_100g, vitamin_a_100g, vitamin_c_100g, vitamin_d_100g, vitamin_b12_100g, vitamin_b6_100g, folate_100g, variant_group_id, reference_portions, prep_minutes, cook_minutes, notes, image_path, favorite, last_cooked_at, cook_count, created_at, updated_at FROM foods WHERE id = ?
`

func (q *Queries) GetFood(ctx context.Context, id int64) (Food, error) {
	row := q.db.QueryRowContext(ctx, getFood, id)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Role,
		&i.Source,
		&i.Barcode,
		&i.OffID,
		&i.FdcID,
		&i.Kcal100g,
		&i.Protein100g,
		&i.Fat100g,
		&i.Carbs100g,
		&i.Fiber100g,
		&i.Sodium100g,
		&i.SaturatedFat100g,
		&i.TransFat100g,
		&i.Cholesterol100g,
		&i.Sugar100g,
		&i.Potassium100g,
		&i.Calcium100g,
		&i.Iron100g,
		&i.Magnesium100g,
		&i.Phosphorus100g,
		&i.Zinc100g,
		&i.VitaminA100g,
		&i.VitaminC100g,
		&i.VitaminD100g,
		&i.VitaminB12100g,
		&i.VitaminB6100g,
		&i.Folate100g,
		&i.VariantGroupID,
		&i.ReferencePortions,
		&i.PrepMinutes,
		&i.CookMinutes,
		&i.Notes,
		&i.ImagePath,
		&i.Favorite,
		&i.LastCookedAt,
		&i.CookCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFoodComponents = `-- name: ListFoodComponents :many
SELECT fc.id, fc.parent_id, fc.child_id, fc.amount, fc.unit, fc.grams, fc.sort_order,
       f.name AS child_name, f.kind AS child_kind
FROM food_components fc
JOIN foods f ON f.id = fc.child_id
WHERE fc.parent_id = ?
ORDER BY fc.sort_order, fc.id
`

type ListFoodComponentsRow struct {
	ID        int64
	ParentID  int64
	ChildID   int64
	Amount    float64
	Unit      string
	Grams     float64
	SortOrder int64
	ChildName string
	ChildKind string
}

func (q *Queries) ListFoodComponents(ctx context.Context, parentID int64) ([]ListFoodComponentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFoodComponents, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFoodComponentsRow{}
	for rows.Next() {
		var i ListFoodComponentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.ChildID,
			&i.Amount,
			&i.Unit,
			&i.Grams,
			&i.SortOrder,
			&i.ChildName,
			&i.ChildKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoodInstructions = `-- name: ListFoodInstructions :many
SELECT id, food_id, step_number, text FROM food_instructions WHERE food_id = ? ORDER BY step_number
`

func (q *Queries) ListFoodInstructions(ctx context.Context, foodID int64) ([]FoodInstruction, error) {
	rows, err := q.db.QueryContext(ctx, listFoodInstructions, foodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FoodInstruction{}
	for rows.Next() {
		var i FoodInstruction
		if err := rows.Scan(
			&i.ID,
			&i.FoodID,
			&i.StepNumber,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoodPortions = `-- name: ListFoodPortions :many
SELECT food_id, unit, grams
FROM food_portions
WHERE food_id = ?
ORDER BY unit
`

func (q *Queries) ListFoodPortions(ctx context.Context, foodID int64) ([]FoodPortion, error) {
	rows, err := q.db.QueryContext(ctx, listFoodPortions, foodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FoodPortion{}
	for rows.Next() {
		var i FoodPortion
		if err := rows.Scan(&i.FoodID, &i.Unit, &i.Grams); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoodTags = `-- name: ListFoodTags :many
SELECT food_id, tag FROM food_tags WHERE food_id = ? ORDER BY tag
`

func (q *Queries) ListFoodTags(ctx context.Context, foodID int64) ([]FoodTag, error) {
	rows, err := q.db.QueryContext(ctx, listFoodTags, foodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FoodTag{}
	for rows.Next() {
		var i FoodTag
		if err := rows.Scan(&i.FoodID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForgottenFoods = `-- name: ListForgottenFoods :many
SELECT id, name, kind, role, source, barcode, off_id, fdc_id, kcal_100g, protein_100g, fat_100g, carbs_100g, fiber_100g, sodium_100g, saturated_fat_100g, trans_fat_100g, cholesterol_100g, sugar_100g, potassium_100g, calcium_100g, iron_100g, magnesium_100g, phosphorus_100g, zinc_100g, vitamin_a_100g, vitamin_c_100g, vitamin_d_100g, vitamin_b12_100g, vitamin_b6_100g, folate_100g, variant_group_id, reference_portions, prep_minutes, cook_minutes, notes, image_path, favorite, last_cooked_at, cook_count, created_at, updated_at FROM foods
WHERE kind = 'composed' AND (last_cooked_at IS NULL OR last_cooked_at < ?)
ORDER BY (last_cooked_at IS NOT NULL), last_cooked_at ASC, name ASC
LIMIT ?
`

type ListForgottenFoodsParams struct {
	LastCookedAt sql.NullString
	Limit        int64
}

func (q *Queries) ListForgottenFoods(ctx context.Context, arg ListForgottenFoodsParams) ([]Food, error) {
	rows, err := q.db.QueryContext(ctx, listForgottenFoods, arg.LastCookedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Food{}
	for rows.Next() {
		var i Food
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Role,
			&i.Source,
			&i.Barcode,
			&i.OffID,
			&i.FdcID,
			&i.Kcal100g,
			&i.Protein100g,
			&i.Fat100g,
			&i.Carbs100g,
			&i.Fiber100g,
			&i.Sodium100g,
			&i.SaturatedFat100g,
			&i.TransFat100g,
			&i.Cholesterol100g,
			&i.Sugar100g,
			&i.Potassium100g,
			&i.Calcium100g,
			&i.Iron100g,
			&i.Magnesium100g,
			&i.Phosphorus100g,
			&i.Zinc100g,
			&i.VitaminA100g,
			&i.VitaminC100g,
			&i.VitaminD100g,
			&i.VitaminB12100g,
			&i.VitaminB6100g,
			&i.Folate100g,
			&i.VariantGroupID,
			&i.ReferencePortions,
			&i.PrepMinutes,
			&i.CookMinutes,
			&i.Notes,
			&i.ImagePath,
			&i.Favorite,
			&i.LastCookedAt,
			&i.CookCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMostCookedFoods = `-- name: ListMostCookedFoods :many
SELECT id, name, kind, role, source, barcode, off_id, fdc_id, kcal_100g, protein_100g, fat_100g, carbs_100g, fiber_100g, sodium_100g, saturated_fat_100g, trans_fat_100g, cholesterol_100g, sugar_100g, potassium_100g, calcium_100g, iron_100g, magnesium_100g, phosphorus_100g, zinc_100g, vitamin_a_100g, vitamin_c_100g, vitamin_d_100g, vitamin_b12_100g, vitamin_b6_100g, folate_100g, variant_group_id, reference_portions, prep_minutes, cook_minutes, notes, image_path, favorite, last_cooked_at, cook_count, created_at, updated_at FROM foods
WHERE kind = 'composed' AND cook_count > 0
ORDER BY cook_count DESC, last_cooked_at DESC, name ASC
LIMIT ?
`

func (q *Queries) ListMostCookedFoods(ctx context.Context, limit int64) ([]Food, error) {
	rows, err := q.db.QueryContext(ctx, listMostCookedFoods, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Food{}
	for rows.Next() {
		var i Food
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Role,
			&i.Source,
			&i.Barcode,
			&i.OffID,
			&i.FdcID,
			&i.Kcal100g,
			&i.Protein100g,
			&i.Fat100g,
			&i.Carbs100g,
			&i.Fiber100g,
			&i.Sodium100g,
			&i.SaturatedFat100g,
			&i.TransFat100g,
			&i.Cholesterol100g,
			&i.Sugar100g,
			&i.Potassium100g,
			&i.Calcium100g,
			&i.Iron100g,
			&i.Magnesium100g,
			&i.Phosphorus100g,
			&i.Zinc100g,
			&i.VitaminA100g,
			&i.VitaminC100g,
			&i.VitaminD100g,
			&i.VitaminB12100g,
			&i.VitaminB6100g,
			&i.Folate100g,
			&i.VariantGroupID,
			&i.ReferencePortions,
			&i.PrepMinutes,
			&i.CookMinutes,
			&i.Notes,
			&i.ImagePath,
			&i.Favorite,
			&i.LastCookedAt,
			&i.CookCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiblingFoods = `-- name: ListSiblingFoods :many
SELECT id, name, kind, role, source, barcode, off_id, fdc_id, kcal_100g, protein_100g, fat_100g, carbs_100g, fiber_100g, sodium_100g, saturated_fat_100g, trans_fat_100g, cholesterol_100g, sugar_100g, potassium_100g, calcium_100g, iron_100g, magnesium_100g, phosphorus_100g, zinc_100g, vitamin_a_100g, vitamin_c_100g, vitamin_d_100g, vitamin_b12_100g, vitamin_b6_100g, folate_100g, variant_group_id, reference_portions, prep_minutes, cook_minutes, notes, image_path, favorite, last_cooked_at, cook_count, created_at, updated_at FROM foods
WHERE kind = 'composed' AND variant_group_id = ? AND id != ?
ORDER BY name
`

type ListSiblingFoodsParams struct {
	VariantGroupID sql.NullInt64
	ID             int64
}

func (q *Queries) ListSiblingFoods(ctx context.Context, arg ListSiblingFoodsParams) ([]Food, error) {
	rows, err := q.db.QueryContext(ctx, listSiblingFoods, arg.VariantGroupID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Food{}
	for rows.Next() {
		var i Food
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Role,
			&i.Source,
			&i.Barcode,
			&i.OffID,
			&i.FdcID,
			&i.Kcal100g,
			&i.Protein100g,
			&i.Fat100g,
			&i.Carbs100g,
			&i.Fiber100g,
			&i.Sodium100g,
			&i.SaturatedFat100g,
			&i.TransFat100g,
			&i.Cholesterol100g,
			&i.Sugar100g,
			&i.Potassium100g,
			&i.Calcium100g,
			&i.Iron100g,
			&i.Magnesium100g,
			&i.Phosphorus100g,
			&i.Zinc100g,
			&i.VitaminA100g,
			&i.VitaminC100g,
			&i.VitaminD100g,
			&i.VitaminB12100g,
			&i.VitaminB6100g,
			&i.Folate100g,
			&i.VariantGroupID,
			&i.ReferencePortions,
			&i.PrepMinutes,
			&i.CookMinutes,
			&i.Notes,
			&i.ImagePath,
			&i.Favorite,
			&i.LastCookedAt,
			&i.CookCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFoodCooked = `-- name: MarkFoodCooked :exec
UPDATE foods
SET last_cooked_at = ?,
    cook_count     = cook_count + 1,
    updated_at     = datetime('now')
WHERE id = ?
`

type MarkFoodCookedParams struct {
	LastCookedAt sql.NullString
	ID           int64
}

func (q *Queries) MarkFoodCooked(ctx context.Context, arg MarkFoodCookedParams) error {
	_, err := q.db.ExecContext(ctx, markFoodCooked, arg.LastCookedAt, arg.ID)
	return err
}

const setFoodFavorite = `-- name: SetFoodFavorite :one
UPDATE foods SET
    favorite   = ?,
    updated_at = datetime('now')
WHERE id = ?
RETURNING id, name, kind, role, source, barcode, off_id, fdc_id, kcal_100g, protein_100g, fat_100g, carbs_100g, fiber_100g, sodium_100g, saturated_fat_100g, trans_fat_100g, cholesterol_100g, sugar_100g, potassium_100g, calcium_100g, iron_100g, magnesium_100g, phosphorus_100g, zinc_100g, vitamin_a_100g, vitamin_c_100g, vitamin_d_100g, vitamin_b12_100g, vitamin_b6_100g, folate_100g, variant_group_id, reference_portions, prep_minutes, cook_minutes, notes, image_path, favorite, last_cooked_at, cook_count, created_at, updated_at
`

type SetFoodFavoriteParams struct {
	Favorite int64
	ID       int64
}

func (q *Queries) SetFoodFavorite(ctx context.Context, arg SetFoodFavoriteParams) (Food, error) {
	row := q.db.QueryRowContext(ctx, setFoodFavorite, arg.Favorite, arg.ID)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Role,
		&i.Source,
		&i.Barcode,
		&i.OffID,
		&i.FdcID,
		&i.Kcal100g,
		&i.Protein100g,
		&i.Fat100g,
		&i.Carbs100g,
		&i.Fiber100g,
		&i.Sodium100g,
		&i.SaturatedFat100g,
		&i.TransFat100g,
		&i.Cholesterol100g,
		&i.Sugar100g,
		&i.Potassium100g,
		&i.Calcium100g,
		&i.Iron100g,
		&i.Magnesium100g,
		&i.Phosphorus100g,
		&i.Zinc100g,
		&i.VitaminA100g,
		&i.VitaminC100g,
		&i.VitaminD100g,
		&i.VitaminB12100g,
		&i.VitaminB6100g,
		&i.Folate100g,
		&i.VariantGroupID,
		&i.ReferencePortions,
		&i.PrepMinutes,
		&i.CookMinutes,
		&i.Notes,
		&i.ImagePath,
		&i.Favorite,
		&i.LastCookedAt,
		&i.CookCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFood = `-- name: UpdateFood :one
UPDATE foods SET
    name               = ?,
    role               = ?,
    source             = ?,
    barcode            = ?,
    off_id             = ?,
    fdc_id             = ?,
    image_path         = ?,
    kcal_100g          = ?,
    protein_100g       = ?,
    fat_100g           = ?,
    carbs_100g         = ?,
    fiber_100g         = ?,
    sodium_100g        = ?,
    saturated_fat_100g = ?,
    trans_fat_100g     = ?,
    cholesterol_100g   = ?,
    sugar_100g         = ?,
    potassium_100g     = ?,
    calcium_100g       = ?,
    iron_100g          = ?,
    magnesium_100g     = ?,
    phosphorus_100g    = ?,
    zinc_100g          = ?,
    vitamin_a_100g     = ?,
    vitamin_c_100g     = ?,
    vitamin_d_100g     = ?,
    vitamin_b12_100g   = ?,
    vitamin_b6_100g    = ?,
    folate_100g        = ?,
    variant_group_id   = ?,
    reference_portions = ?,
    prep_minutes       = ?,
    cook_minutes       = ?,
    notes              = ?,
    favorite           = ?,
    updated_at         = datetime('now')
WHERE id = ?
RETURNING id, name, kind, role, source, barcode, off_id, fdc_id, kcal_100g, protein_100g, fat_100g, carbs_100g, fiber_100g, sodium_100g, saturated_fat_100g, trans_fat_100g, cholesterol_100g, sugar_100g, potassium_100g, calcium_100g, iron_100g, magnesium_100g, phosphorus_100g, zinc_100g, vitamin_a_100g, vitamin_c_100g, vitamin_d_100g, vitamin_b12_100g, vitamin_b6_100g, folate_100g, variant_group_id, reference_portions, prep_minutes, cook_minutes, notes, image_path, favorite, last_cooked_at, cook_count, created_at, updated_at
`

type UpdateFoodParams struct {
	Name              string
	Role              sql.NullString
	Source            sql.NullString
	Barcode           sql.NullString
	OffID             sql.NullString
	FdcID             sql.NullString
	ImagePath         sql.NullString
	Kcal100g          sql.NullFloat64
	Protein100g       sql.NullFloat64
	Fat100g           sql.NullFloat64
	Carbs100g         sql.NullFloat64
	Fiber100g         sql.NullFloat64
	Sodium100g        sql.NullFloat64
	SaturatedFat100g  sql.NullFloat64
	TransFat100g      sql.NullFloat64
	Cholesterol100g   sql.NullFloat64
	Sugar100g         sql.NullFloat64
	Potassium100g     sql.NullFloat64
	Calcium100g       sql.NullFloat64
	Iron100g          sql.NullFloat64
	Magnesium100g     sql.NullFloat64
	Phosphorus100g    sql.NullFloat64
	Zinc100g          sql.NullFloat64
	VitaminA100g      sql.NullFloat64
	VitaminC100g      sql.NullFloat64
	VitaminD100g      sql.NullFloat64
	VitaminB12100g    sql.NullFloat64
	VitaminB6100g     sql.NullFloat64
	Folate100g        sql.NullFloat64
	VariantGroupID    sql.NullInt64
	ReferencePortions sql.NullFloat64
	PrepMinutes       sql.NullInt64
	CookMinutes       sql.NullInt64
	Notes             sql.NullString
	Favorite          int64
	ID                int64
}

func (q *Queries) UpdateFood(ctx context.Context, arg UpdateFoodParams) (Food, error) {
	row := q.db.QueryRowContext(ctx, updateFood,
		arg.Name,
		arg.Role,
		arg.Source,
		arg.Barcode,
		arg.OffID,
		arg.FdcID,
		arg.ImagePath,
		arg.Kcal100g,
		arg.Protein100g,
		arg.Fat100g,
		arg.Carbs100g,
		arg.Fiber100g,
		arg.Sodium100g,
		arg.SaturatedFat100g,
		arg.TransFat100g,
		arg.Cholesterol100g,
		arg.Sugar100g,
		arg.Potassium100g,
		arg.Calcium100g,
		arg.Iron100g,
		arg.Magnesium100g,
		arg.Phosphorus100g,
		arg.Zinc100g,
		arg.VitaminA100g,
		arg.VitaminC100g,
		arg.VitaminD100g,
		arg.VitaminB12100g,
		arg.VitaminB6100g,
		arg.Folate100g,
		arg.VariantGroupID,
		arg.ReferencePortions,
		arg.PrepMinutes,
		arg.CookMinutes,
		arg.Notes,
		arg.Favorite,
		arg.ID,
	)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Role,
		&i.Source,
		&i.Barcode,
		&i.OffID,
		&i.FdcID,
		&i.Kcal100g,
		&i.Protein100g,
		&i.Fat100g,
		&i.Carbs100g,
		&i.Fiber100g,
		&i.Sodium100g,
		&i.SaturatedFat100g,
		&i.TransFat100g,
		&i.Cholesterol100g,
		&i.Sugar100g,
		&i.Potassium100g,
		&i.Calcium100g,
		&i.Iron100g,
		&i.Magnesium100g,
		&i.Phosphorus100g,
		&i.Zinc100g,
		&i.VitaminA100g,
		&i.VitaminC100g,
		&i.VitaminD100g,
		&i.VitaminB12100g,
		&i.VitaminB6100g,
		&i.Folate100g,
		&i.VariantGroupID,
		&i.ReferencePortions,
		&i.PrepMinutes,
		&i.CookMinutes,
		&i.Notes,
		&i.ImagePath,
		&i.Favorite,
		&i.LastCookedAt,
		&i.CookCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFoodPortion = `-- name: UpsertFoodPortion :exec
INSERT INTO food_portions (food_id, unit, grams)
VALUES (?, ?, ?)
ON CONFLICT (food_id, unit) DO UPDATE SET grams = excluded.grams
`

type UpsertFoodPortionParams struct {
	FoodID int64
	Unit   string
	Grams  float64
}

func (q *Queries) UpsertFoodPortion(ctx context.Context, arg UpsertFoodPortionParams) error {
	_, err := q.db.ExecContext(ctx, upsertFoodPortion, arg.FoodID, arg.Unit, arg.Grams)
	return err
}
