// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingredients.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO ingredients (
    name, source, barcode, off_id, fdc_id, image_path,
    kcal_100g, protein_100g, fat_100g, carbs_100g, fiber_100g, sodium_100g
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, source, barcode, off_id, fdc_id, image_path, kcal_100g, protein_100g, fat_100g, carbs_100g, fiber_100g, sodium_100g, created_at, updated_at
`

type CreateIngredientParams struct {
	Name        string
	Source      string
	Barcode     sql.NullString
	OffID       sql.NullString
	FdcID       sql.NullString
	ImagePath   sql.NullString
	Kcal100g    float64
	Protein100g float64
	Fat100g     float64
	Carbs100g   float64
	Fiber100g   float64
	Sodium100g  float64
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, createIngredient,
		arg.Name,
		arg.Source,
		arg.Barcode,
		arg.OffID,
		arg.FdcID,
		arg.ImagePath,
		arg.Kcal100g,
		arg.Protein100g,
		arg.Fat100g,
		arg.Carbs100g,
		arg.Fiber100g,
		arg.Sodium100g,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.Barcode,
		&i.OffID,
		&i.FdcID,
		&i.ImagePath,
		&i.Kcal100g,
		&i.Protein100g,
		&i.Fat100g,
		&i.Carbs100g,
		&i.Fiber100g,
		&i.Sodium100g,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIngredient = `-- name: DeleteIngredient :execresult
DELETE FROM ingredients WHERE id = ?
`

func (q *Queries) DeleteIngredient(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteIngredient, id)
}

const getIngredient = `-- name: GetIngredient :one
SELECT id, name, source, barcode, off_id, fdc_id, image_path, kcal_100g, protein_100g, fat_100g, carbs_100g, fiber_100g, sodium_100g, created_at, updated_at FROM ingredients WHERE id = ?
`

func (q *Queries) GetIngredient(ctx context.Context, id int64) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, getIngredient, id)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.Barcode,
		&i.OffID,
		&i.FdcID,
		&i.ImagePath,
		&i.Kcal100g,
		&i.Protein100g,
		&i.Fat100g,
		&i.Carbs100g,
		&i.Fiber100g,
		&i.Sodium100g,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIngredient = `-- name: UpdateIngredient :one
UPDATE ingredients SET
    name         = ?,
    source       = ?,
    barcode      = ?,
    off_id       = ?,
    fdc_id       = ?,
    image_path   = ?,
    kcal_100g    = ?,
    protein_100g = ?,
    fat_100g     = ?,
    carbs_100g   = ?,
    fiber_100g   = ?,
    sodium_100g  = ?,
    updated_at   = datetime('now')
WHERE id = ?
RETURNING id, name, source, barcode, off_id, fdc_id, image_path, kcal_100g, protein_100g, fat_100g, carbs_100g, fiber_100g, sodium_100g, created_at, updated_at
`

type UpdateIngredientParams struct {
	Name        string
	Source      string
	Barcode     sql.NullString
	OffID       sql.NullString
	FdcID       sql.NullString
	ImagePath   sql.NullString
	Kcal100g    float64
	Protein100g float64
	Fat100g     float64
	Carbs100g   float64
	Fiber100g   float64
	Sodium100g  float64
	ID          int64
}

func (q *Queries) UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, updateIngredient,
		arg.Name,
		arg.Source,
		arg.Barcode,
		arg.OffID,
		arg.FdcID,
		arg.ImagePath,
		arg.Kcal100g,
		arg.Protein100g,
		arg.Fat100g,
		arg.Carbs100g,
		arg.Fiber100g,
		arg.Sodium100g,
		arg.ID,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.Barcode,
		&i.OffID,
		&i.FdcID,
		&i.ImagePath,
		&i.Kcal100g,
		&i.Protein100g,
		&i.Fat100g,
		&i.Carbs100g,
		&i.Fiber100g,
		&i.Sodium100g,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
