// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type AiConversation struct {
	ID        int64
	WeekID    sql.NullInt64
	Title     sql.NullString
	CreatedAt string
	UpdatedAt string
}

type AiMessage struct {
	ID             int64
	ConversationID int64
	Role           string
	Content        string
	CreatedAt      string
}

type AppSetting struct {
	Key       string
	Value     string
	Encrypted int64
	UpdatedAt string
}

type Food struct {
	ID                int64
	Name              string
	Kind              string
	Role              sql.NullString
	Source            sql.NullString
	Barcode           sql.NullString
	OffID             sql.NullString
	FdcID             sql.NullString
	Kcal100g          sql.NullFloat64
	Protein100g       sql.NullFloat64
	Fat100g           sql.NullFloat64
	Carbs100g         sql.NullFloat64
	Fiber100g         sql.NullFloat64
	Sodium100g        sql.NullFloat64
	SaturatedFat100g  sql.NullFloat64
	TransFat100g      sql.NullFloat64
	Cholesterol100g   sql.NullFloat64
	Sugar100g         sql.NullFloat64
	Potassium100g     sql.NullFloat64
	Calcium100g       sql.NullFloat64
	Iron100g          sql.NullFloat64
	Magnesium100g     sql.NullFloat64
	Phosphorus100g    sql.NullFloat64
	Zinc100g          sql.NullFloat64
	VitaminA100g      sql.NullFloat64
	VitaminC100g      sql.NullFloat64
	VitaminD100g      sql.NullFloat64
	VitaminB12100g    sql.NullFloat64
	VitaminB6100g     sql.NullFloat64
	Folate100g        sql.NullFloat64
	VariantGroupID    sql.NullInt64
	ReferencePortions sql.NullFloat64
	PrepMinutes       sql.NullInt64
	CookMinutes       sql.NullInt64
	Notes             sql.NullString
	ImagePath         sql.NullString
	Favorite          int64
	LastCookedAt      sql.NullString
	CookCount         int64
	CreatedAt         string
	UpdatedAt         string
}

type FoodComponent struct {
	ID        int64
	ParentID  int64
	ChildID   int64
	Amount    float64
	Unit      string
	Grams     float64
	SortOrder int64
}

type FoodInstruction struct {
	ID         int64
	FoodID     int64
	StepNumber int64
	Text       string
}

type FoodPortion struct {
	FoodID int64
	Unit   string
	Grams  float64
}

type FoodTag struct {
	FoodID int64
	Tag    string
}

type FoodsFt struct {
	Name string
}

type Plate struct {
	ID        int64
	WeekID    int64
	Day       int64
	SlotID    int64
	Note      sql.NullString
	CreatedAt string
	Skipped   int64
	Date      string
}

type PlateComponent struct {
	ID        int64
	PlateID   int64
	FoodID    int64
	Portions  float64
	SortOrder int64
}

type PlateFeedback struct {
	PlateID int64
	Status  string
	Note    sql.NullString
	RatedAt string
}

type Template struct {
	ID        int64
	Name      string
	CreatedAt string
}

type TemplateComponent struct {
	ID         int64
	TemplateID int64
	FoodID     int64
	Portions   float64
	SortOrder  int64
	DayOffset  int64
}

type TimeSlot struct {
	ID        int64
	NameKey   string
	Icon      string
	SortOrder int64
	Active    int64
}

type UserProfile struct {
	ID                  int64
	KcalTarget          sql.NullFloat64
	ProteinPct          sql.NullFloat64
	FatPct              sql.NullFloat64
	CarbsPct            sql.NullFloat64
	DietaryRestrictions string
	Preferences         string
	SystemPrompt        sql.NullString
	Locale              string
	UpdatedAt           string
}

type VariantGroup struct {
	ID        int64
	Name      string
	CreatedAt string
}

type Week struct {
	ID         int64
	Year       int64
	WeekNumber int64
	CreatedAt  string
}
