// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: placeholder.sql

package sqlcgen

import (
	"context"
)

const schemaVersion = `-- name: SchemaVersion :one

SELECT 1 AS version
`

// Placeholder query so sqlc has something to generate in Phase 0. Real
// aggregate queries replace this starting in Phase 1 (ingredients).
func (q *Queries) SchemaVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, schemaVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}
