// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: planner.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countPlatesUsingComponent = `-- name: CountPlatesUsingComponent :one
SELECT COUNT(*) FROM plate_components WHERE component_id = ?
`

func (q *Queries) CountPlatesUsingComponent(ctx context.Context, componentID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlatesUsingComponent, componentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlatesUsingTimeSlot = `-- name: CountPlatesUsingTimeSlot :one
SELECT COUNT(*) FROM plates WHERE slot_id = ?
`

func (q *Queries) CountPlatesUsingTimeSlot(ctx context.Context, slotID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlatesUsingTimeSlot, slotID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWeeks = `-- name: CountWeeks :one
SELECT COUNT(*) FROM weeks
`

func (q *Queries) CountWeeks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWeeks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlate = `-- name: CreatePlate :one
INSERT INTO plates (week_id, day, slot_id, note)
VALUES (?, ?, ?, ?)
RETURNING id, week_id, day, slot_id, note, created_at, skipped
`

type CreatePlateParams struct {
	WeekID int64
	Day    int64
	SlotID int64
	Note   sql.NullString
}

func (q *Queries) CreatePlate(ctx context.Context, arg CreatePlateParams) (Plate, error) {
	row := q.db.QueryRowContext(ctx, createPlate,
		arg.WeekID,
		arg.Day,
		arg.SlotID,
		arg.Note,
	)
	var i Plate
	err := row.Scan(
		&i.ID,
		&i.WeekID,
		&i.Day,
		&i.SlotID,
		&i.Note,
		&i.CreatedAt,
		&i.Skipped,
	)
	return i, err
}

const createPlateComponent = `-- name: CreatePlateComponent :one
INSERT INTO plate_components (plate_id, component_id, portions, sort_order)
VALUES (?, ?, ?, ?)
RETURNING id, plate_id, component_id, portions, sort_order
`

type CreatePlateComponentParams struct {
	PlateID     int64
	ComponentID int64
	Portions    float64
	SortOrder   int64
}

func (q *Queries) CreatePlateComponent(ctx context.Context, arg CreatePlateComponentParams) (PlateComponent, error) {
	row := q.db.QueryRowContext(ctx, createPlateComponent,
		arg.PlateID,
		arg.ComponentID,
		arg.Portions,
		arg.SortOrder,
	)
	var i PlateComponent
	err := row.Scan(
		&i.ID,
		&i.PlateID,
		&i.ComponentID,
		&i.Portions,
		&i.SortOrder,
	)
	return i, err
}

const createTimeSlot = `-- name: CreateTimeSlot :one
INSERT INTO time_slots (name_key, icon, sort_order, active)
VALUES (?, ?, ?, ?)
RETURNING id, name_key, icon, sort_order, active
`

type CreateTimeSlotParams struct {
	NameKey   string
	Icon      string
	SortOrder int64
	Active    int64
}

func (q *Queries) CreateTimeSlot(ctx context.Context, arg CreateTimeSlotParams) (TimeSlot, error) {
	row := q.db.QueryRowContext(ctx, createTimeSlot,
		arg.NameKey,
		arg.Icon,
		arg.SortOrder,
		arg.Active,
	)
	var i TimeSlot
	err := row.Scan(
		&i.ID,
		&i.NameKey,
		&i.Icon,
		&i.SortOrder,
		&i.Active,
	)
	return i, err
}

const createWeek = `-- name: CreateWeek :one
INSERT INTO weeks (year, week_number) VALUES (?, ?) RETURNING id, year, week_number, created_at
`

type CreateWeekParams struct {
	Year       int64
	WeekNumber int64
}

func (q *Queries) CreateWeek(ctx context.Context, arg CreateWeekParams) (Week, error) {
	row := q.db.QueryRowContext(ctx, createWeek, arg.Year, arg.WeekNumber)
	var i Week
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.WeekNumber,
		&i.CreatedAt,
	)
	return i, err
}

const deletePlate = `-- name: DeletePlate :execresult
DELETE FROM plates WHERE id = ?
`

func (q *Queries) DeletePlate(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePlate, id)
}

const deletePlateComponent = `-- name: DeletePlateComponent :execresult
DELETE FROM plate_components WHERE id = ?
`

func (q *Queries) DeletePlateComponent(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePlateComponent, id)
}

const deletePlatesByWeek = `-- name: DeletePlatesByWeek :execresult
DELETE FROM plates WHERE week_id = ?
`

func (q *Queries) DeletePlatesByWeek(ctx context.Context, weekID int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePlatesByWeek, weekID)
}

const deleteTimeSlot = `-- name: DeleteTimeSlot :execresult
DELETE FROM time_slots WHERE id = ?
`

func (q *Queries) DeleteTimeSlot(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTimeSlot, id)
}

const getPlate = `-- name: GetPlate :one
SELECT id, week_id, day, slot_id, note, created_at, skipped FROM plates WHERE id = ?
`

func (q *Queries) GetPlate(ctx context.Context, id int64) (Plate, error) {
	row := q.db.QueryRowContext(ctx, getPlate, id)
	var i Plate
	err := row.Scan(
		&i.ID,
		&i.WeekID,
		&i.Day,
		&i.SlotID,
		&i.Note,
		&i.CreatedAt,
		&i.Skipped,
	)
	return i, err
}

const getPlateComponent = `-- name: GetPlateComponent :one
SELECT id, plate_id, component_id, portions, sort_order FROM plate_components WHERE id = ?
`

func (q *Queries) GetPlateComponent(ctx context.Context, id int64) (PlateComponent, error) {
	row := q.db.QueryRowContext(ctx, getPlateComponent, id)
	var i PlateComponent
	err := row.Scan(
		&i.ID,
		&i.PlateID,
		&i.ComponentID,
		&i.Portions,
		&i.SortOrder,
	)
	return i, err
}

const getTimeSlot = `-- name: GetTimeSlot :one
SELECT id, name_key, icon, sort_order, active FROM time_slots WHERE id = ?
`

func (q *Queries) GetTimeSlot(ctx context.Context, id int64) (TimeSlot, error) {
	row := q.db.QueryRowContext(ctx, getTimeSlot, id)
	var i TimeSlot
	err := row.Scan(
		&i.ID,
		&i.NameKey,
		&i.Icon,
		&i.SortOrder,
		&i.Active,
	)
	return i, err
}

const getWeek = `-- name: GetWeek :one
SELECT id, year, week_number, created_at FROM weeks WHERE id = ?
`

func (q *Queries) GetWeek(ctx context.Context, id int64) (Week, error) {
	row := q.db.QueryRowContext(ctx, getWeek, id)
	var i Week
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.WeekNumber,
		&i.CreatedAt,
	)
	return i, err
}

const getWeekByYearAndNumber = `-- name: GetWeekByYearAndNumber :one
SELECT id, year, week_number, created_at FROM weeks WHERE year = ? AND week_number = ?
`

type GetWeekByYearAndNumberParams struct {
	Year       int64
	WeekNumber int64
}

func (q *Queries) GetWeekByYearAndNumber(ctx context.Context, arg GetWeekByYearAndNumberParams) (Week, error) {
	row := q.db.QueryRowContext(ctx, getWeekByYearAndNumber, arg.Year, arg.WeekNumber)
	var i Week
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.WeekNumber,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveTimeSlots = `-- name: ListActiveTimeSlots :many
SELECT id, name_key, icon, sort_order, active FROM time_slots WHERE active = 1 ORDER BY sort_order, id
`

func (q *Queries) ListActiveTimeSlots(ctx context.Context) ([]TimeSlot, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTimeSlots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimeSlot{}
	for rows.Next() {
		var i TimeSlot
		if err := rows.Scan(
			&i.ID,
			&i.NameKey,
			&i.Icon,
			&i.SortOrder,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlateComponentsByPlate = `-- name: ListPlateComponentsByPlate :many
SELECT id, plate_id, component_id, portions, sort_order FROM plate_components WHERE plate_id = ? ORDER BY sort_order, id
`

func (q *Queries) ListPlateComponentsByPlate(ctx context.Context, plateID int64) ([]PlateComponent, error) {
	rows, err := q.db.QueryContext(ctx, listPlateComponentsByPlate, plateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlateComponent{}
	for rows.Next() {
		var i PlateComponent
		if err := rows.Scan(
			&i.ID,
			&i.PlateID,
			&i.ComponentID,
			&i.Portions,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlateComponentsByWeek = `-- name: ListPlateComponentsByWeek :many
SELECT pc.id, pc.plate_id, pc.component_id, pc.portions, pc.sort_order
FROM plate_components pc
JOIN plates p ON p.id = pc.plate_id
WHERE p.week_id = ?
ORDER BY p.day, p.slot_id, pc.sort_order, pc.id
`

func (q *Queries) ListPlateComponentsByWeek(ctx context.Context, weekID int64) ([]PlateComponent, error) {
	rows, err := q.db.QueryContext(ctx, listPlateComponentsByWeek, weekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlateComponent{}
	for rows.Next() {
		var i PlateComponent
		if err := rows.Scan(
			&i.ID,
			&i.PlateID,
			&i.ComponentID,
			&i.Portions,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatesByWeek = `-- name: ListPlatesByWeek :many
SELECT id, week_id, day, slot_id, note, created_at, skipped FROM plates WHERE week_id = ? ORDER BY day, slot_id, id
`

func (q *Queries) ListPlatesByWeek(ctx context.Context, weekID int64) ([]Plate, error) {
	rows, err := q.db.QueryContext(ctx, listPlatesByWeek, weekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plate{}
	for rows.Next() {
		var i Plate
		if err := rows.Scan(
			&i.ID,
			&i.WeekID,
			&i.Day,
			&i.SlotID,
			&i.Note,
			&i.CreatedAt,
			&i.Skipped,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeSlots = `-- name: ListTimeSlots :many
SELECT id, name_key, icon, sort_order, active FROM time_slots ORDER BY sort_order, id
`

func (q *Queries) ListTimeSlots(ctx context.Context) ([]TimeSlot, error) {
	rows, err := q.db.QueryContext(ctx, listTimeSlots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimeSlot{}
	for rows.Next() {
		var i TimeSlot
		if err := rows.Scan(
			&i.ID,
			&i.NameKey,
			&i.Icon,
			&i.SortOrder,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeeks = `-- name: ListWeeks :many
SELECT id, year, week_number, created_at FROM weeks ORDER BY year DESC, week_number DESC LIMIT ? OFFSET ?
`

type ListWeeksParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListWeeks(ctx context.Context, arg ListWeeksParams) ([]Week, error) {
	rows, err := q.db.QueryContext(ctx, listWeeks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Week{}
	for rows.Next() {
		var i Week
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.WeekNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPlateSkipped = `-- name: SetPlateSkipped :one
UPDATE plates SET
    skipped = ?,
    note    = ?
WHERE id = ?
RETURNING id, week_id, day, slot_id, note, created_at, skipped
`

type SetPlateSkippedParams struct {
	Skipped int64
	Note    sql.NullString
	ID      int64
}

func (q *Queries) SetPlateSkipped(ctx context.Context, arg SetPlateSkippedParams) (Plate, error) {
	row := q.db.QueryRowContext(ctx, setPlateSkipped, arg.Skipped, arg.Note, arg.ID)
	var i Plate
	err := row.Scan(
		&i.ID,
		&i.WeekID,
		&i.Day,
		&i.SlotID,
		&i.Note,
		&i.CreatedAt,
		&i.Skipped,
	)
	return i, err
}

const updatePlate = `-- name: UpdatePlate :one
UPDATE plates SET
    day     = ?,
    slot_id = ?,
    note    = ?
WHERE id = ?
RETURNING id, week_id, day, slot_id, note, created_at, skipped
`

type UpdatePlateParams struct {
	Day    int64
	SlotID int64
	Note   sql.NullString
	ID     int64
}

func (q *Queries) UpdatePlate(ctx context.Context, arg UpdatePlateParams) (Plate, error) {
	row := q.db.QueryRowContext(ctx, updatePlate,
		arg.Day,
		arg.SlotID,
		arg.Note,
		arg.ID,
	)
	var i Plate
	err := row.Scan(
		&i.ID,
		&i.WeekID,
		&i.Day,
		&i.SlotID,
		&i.Note,
		&i.CreatedAt,
		&i.Skipped,
	)
	return i, err
}

const updatePlateComponent = `-- name: UpdatePlateComponent :one
UPDATE plate_components SET
    component_id = ?,
    portions     = ?
WHERE id = ?
RETURNING id, plate_id, component_id, portions, sort_order
`

type UpdatePlateComponentParams struct {
	ComponentID int64
	Portions    float64
	ID          int64
}

func (q *Queries) UpdatePlateComponent(ctx context.Context, arg UpdatePlateComponentParams) (PlateComponent, error) {
	row := q.db.QueryRowContext(ctx, updatePlateComponent, arg.ComponentID, arg.Portions, arg.ID)
	var i PlateComponent
	err := row.Scan(
		&i.ID,
		&i.PlateID,
		&i.ComponentID,
		&i.Portions,
		&i.SortOrder,
	)
	return i, err
}

const updateTimeSlot = `-- name: UpdateTimeSlot :one
UPDATE time_slots SET
    name_key   = ?,
    icon       = ?,
    sort_order = ?,
    active     = ?
WHERE id = ?
RETURNING id, name_key, icon, sort_order, active
`

type UpdateTimeSlotParams struct {
	NameKey   string
	Icon      string
	SortOrder int64
	Active    int64
	ID        int64
}

func (q *Queries) UpdateTimeSlot(ctx context.Context, arg UpdateTimeSlotParams) (TimeSlot, error) {
	row := q.db.QueryRowContext(ctx, updateTimeSlot,
		arg.NameKey,
		arg.Icon,
		arg.SortOrder,
		arg.Active,
		arg.ID,
	)
	var i TimeSlot
	err := row.Scan(
		&i.ID,
		&i.NameKey,
		&i.Icon,
		&i.SortOrder,
		&i.Active,
	)
	return i, err
}
