// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: planner.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countPlatesUsingFood = `-- name: CountPlatesUsingFood :one
SELECT COUNT(*) FROM plate_components WHERE food_id = ?
`

func (q *Queries) CountPlatesUsingFood(ctx context.Context, foodID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlatesUsingFood, foodID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlatesUsingTimeSlot = `-- name: CountPlatesUsingTimeSlot :one
SELECT COUNT(*) FROM plates WHERE slot_id = ?
`

func (q *Queries) CountPlatesUsingTimeSlot(ctx context.Context, slotID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlatesUsingTimeSlot, slotID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlate = `-- name: CreatePlate :one
INSERT INTO plates (slot_id, note, date)
VALUES (?, ?, ?)
RETURNING id, slot_id, note, created_at, skipped, date
`

type CreatePlateParams struct {
	SlotID int64
	Note   sql.NullString
	Date   string
}

func (q *Queries) CreatePlate(ctx context.Context, arg CreatePlateParams) (Plate, error) {
	row := q.db.QueryRowContext(ctx, createPlate, arg.SlotID, arg.Note, arg.Date)
	var i Plate
	err := row.Scan(
		&i.ID,
		&i.SlotID,
		&i.Note,
		&i.CreatedAt,
		&i.Skipped,
		&i.Date,
	)
	return i, err
}

const createPlateComponent = `-- name: CreatePlateComponent :one
INSERT INTO plate_components (plate_id, food_id, portions, sort_order)
VALUES (?, ?, ?, ?)
RETURNING id, plate_id, food_id, portions, sort_order
`

type CreatePlateComponentParams struct {
	PlateID   int64
	FoodID    int64
	Portions  float64
	SortOrder int64
}

func (q *Queries) CreatePlateComponent(ctx context.Context, arg CreatePlateComponentParams) (PlateComponent, error) {
	row := q.db.QueryRowContext(ctx, createPlateComponent,
		arg.PlateID,
		arg.FoodID,
		arg.Portions,
		arg.SortOrder,
	)
	var i PlateComponent
	err := row.Scan(
		&i.ID,
		&i.PlateID,
		&i.FoodID,
		&i.Portions,
		&i.SortOrder,
	)
	return i, err
}

const createTimeSlot = `-- name: CreateTimeSlot :one
INSERT INTO time_slots (name_key, icon, sort_order, active)
VALUES (?, ?, ?, ?)
RETURNING id, name_key, icon, sort_order, active
`

type CreateTimeSlotParams struct {
	NameKey   string
	Icon      string
	SortOrder int64
	Active    int64
}

func (q *Queries) CreateTimeSlot(ctx context.Context, arg CreateTimeSlotParams) (TimeSlot, error) {
	row := q.db.QueryRowContext(ctx, createTimeSlot,
		arg.NameKey,
		arg.Icon,
		arg.SortOrder,
		arg.Active,
	)
	var i TimeSlot
	err := row.Scan(
		&i.ID,
		&i.NameKey,
		&i.Icon,
		&i.SortOrder,
		&i.Active,
	)
	return i, err
}

const deletePlate = `-- name: DeletePlate :execresult
DELETE FROM plates WHERE id = ?
`

func (q *Queries) DeletePlate(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePlate, id)
}

const deletePlateComponent = `-- name: DeletePlateComponent :execresult
DELETE FROM plate_components WHERE id = ?
`

func (q *Queries) DeletePlateComponent(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePlateComponent, id)
}

const deleteTimeSlot = `-- name: DeleteTimeSlot :execresult
DELETE FROM time_slots WHERE id = ?
`

func (q *Queries) DeleteTimeSlot(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTimeSlot, id)
}

const getPlate = `-- name: GetPlate :one
SELECT id, slot_id, note, created_at, skipped, date FROM plates WHERE id = ?
`

func (q *Queries) GetPlate(ctx context.Context, id int64) (Plate, error) {
	row := q.db.QueryRowContext(ctx, getPlate, id)
	var i Plate
	err := row.Scan(
		&i.ID,
		&i.SlotID,
		&i.Note,
		&i.CreatedAt,
		&i.Skipped,
		&i.Date,
	)
	return i, err
}

const getPlateComponent = `-- name: GetPlateComponent :one
SELECT id, plate_id, food_id, portions, sort_order FROM plate_components WHERE id = ?
`

func (q *Queries) GetPlateComponent(ctx context.Context, id int64) (PlateComponent, error) {
	row := q.db.QueryRowContext(ctx, getPlateComponent, id)
	var i PlateComponent
	err := row.Scan(
		&i.ID,
		&i.PlateID,
		&i.FoodID,
		&i.Portions,
		&i.SortOrder,
	)
	return i, err
}

const getTimeSlot = `-- name: GetTimeSlot :one
SELECT id, name_key, icon, sort_order, active FROM time_slots WHERE id = ?
`

func (q *Queries) GetTimeSlot(ctx context.Context, id int64) (TimeSlot, error) {
	row := q.db.QueryRowContext(ctx, getTimeSlot, id)
	var i TimeSlot
	err := row.Scan(
		&i.ID,
		&i.NameKey,
		&i.Icon,
		&i.SortOrder,
		&i.Active,
	)
	return i, err
}

const listActiveTimeSlots = `-- name: ListActiveTimeSlots :many
SELECT id, name_key, icon, sort_order, active FROM time_slots WHERE active = 1 ORDER BY sort_order, id
`

func (q *Queries) ListActiveTimeSlots(ctx context.Context) ([]TimeSlot, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTimeSlots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimeSlot{}
	for rows.Next() {
		var i TimeSlot
		if err := rows.Scan(
			&i.ID,
			&i.NameKey,
			&i.Icon,
			&i.SortOrder,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlateComponentsByPlate = `-- name: ListPlateComponentsByPlate :many
SELECT id, plate_id, food_id, portions, sort_order FROM plate_components WHERE plate_id = ? ORDER BY sort_order, id
`

func (q *Queries) ListPlateComponentsByPlate(ctx context.Context, plateID int64) ([]PlateComponent, error) {
	rows, err := q.db.QueryContext(ctx, listPlateComponentsByPlate, plateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlateComponent{}
	for rows.Next() {
		var i PlateComponent
		if err := rows.Scan(
			&i.ID,
			&i.PlateID,
			&i.FoodID,
			&i.Portions,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatesByDate = `-- name: ListPlatesByDate :many
SELECT id, slot_id, note, created_at, skipped, date FROM plates WHERE date = ? ORDER BY slot_id, id
`

func (q *Queries) ListPlatesByDate(ctx context.Context, date string) ([]Plate, error) {
	rows, err := q.db.QueryContext(ctx, listPlatesByDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plate{}
	for rows.Next() {
		var i Plate
		if err := rows.Scan(
			&i.ID,
			&i.SlotID,
			&i.Note,
			&i.CreatedAt,
			&i.Skipped,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatesByDateRange = `-- name: ListPlatesByDateRange :many
SELECT id, slot_id, note, created_at, skipped, date FROM plates WHERE date BETWEEN ? AND ? ORDER BY date, slot_id, id
`

type ListPlatesByDateRangeParams struct {
	FromDate string
	ToDate   string
}

func (q *Queries) ListPlatesByDateRange(ctx context.Context, arg ListPlatesByDateRangeParams) ([]Plate, error) {
	rows, err := q.db.QueryContext(ctx, listPlatesByDateRange, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plate{}
	for rows.Next() {
		var i Plate
		if err := rows.Scan(
			&i.ID,
			&i.SlotID,
			&i.Note,
			&i.CreatedAt,
			&i.Skipped,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeSlots = `-- name: ListTimeSlots :many
SELECT id, name_key, icon, sort_order, active FROM time_slots ORDER BY sort_order, id
`

func (q *Queries) ListTimeSlots(ctx context.Context) ([]TimeSlot, error) {
	rows, err := q.db.QueryContext(ctx, listTimeSlots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimeSlot{}
	for rows.Next() {
		var i TimeSlot
		if err := rows.Scan(
			&i.ID,
			&i.NameKey,
			&i.Icon,
			&i.SortOrder,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPlateSkipped = `-- name: SetPlateSkipped :one
UPDATE plates SET
    skipped = ?,
    note    = ?
WHERE id = ?
RETURNING id, slot_id, note, created_at, skipped, date
`

type SetPlateSkippedParams struct {
	Skipped int64
	Note    sql.NullString
	ID      int64
}

func (q *Queries) SetPlateSkipped(ctx context.Context, arg SetPlateSkippedParams) (Plate, error) {
	row := q.db.QueryRowContext(ctx, setPlateSkipped, arg.Skipped, arg.Note, arg.ID)
	var i Plate
	err := row.Scan(
		&i.ID,
		&i.SlotID,
		&i.Note,
		&i.CreatedAt,
		&i.Skipped,
		&i.Date,
	)
	return i, err
}

const updatePlate = `-- name: UpdatePlate :one
UPDATE plates SET
    slot_id = ?,
    note    = ?,
    date    = ?
WHERE id = ?
RETURNING id, slot_id, note, created_at, skipped, date
`

type UpdatePlateParams struct {
	SlotID int64
	Note   sql.NullString
	Date   string
	ID     int64
}

func (q *Queries) UpdatePlate(ctx context.Context, arg UpdatePlateParams) (Plate, error) {
	row := q.db.QueryRowContext(ctx, updatePlate,
		arg.SlotID,
		arg.Note,
		arg.Date,
		arg.ID,
	)
	var i Plate
	err := row.Scan(
		&i.ID,
		&i.SlotID,
		&i.Note,
		&i.CreatedAt,
		&i.Skipped,
		&i.Date,
	)
	return i, err
}

const updatePlateComponent = `-- name: UpdatePlateComponent :one
UPDATE plate_components SET
    food_id  = ?,
    portions = ?
WHERE id = ?
RETURNING id, plate_id, food_id, portions, sort_order
`

type UpdatePlateComponentParams struct {
	FoodID   int64
	Portions float64
	ID       int64
}

func (q *Queries) UpdatePlateComponent(ctx context.Context, arg UpdatePlateComponentParams) (PlateComponent, error) {
	row := q.db.QueryRowContext(ctx, updatePlateComponent, arg.FoodID, arg.Portions, arg.ID)
	var i PlateComponent
	err := row.Scan(
		&i.ID,
		&i.PlateID,
		&i.FoodID,
		&i.Portions,
		&i.SortOrder,
	)
	return i, err
}

const updateTimeSlot = `-- name: UpdateTimeSlot :one
UPDATE time_slots SET
    name_key   = ?,
    icon       = ?,
    sort_order = ?,
    active     = ?
WHERE id = ?
RETURNING id, name_key, icon, sort_order, active
`

type UpdateTimeSlotParams struct {
	NameKey   string
	Icon      string
	SortOrder int64
	Active    int64
	ID        int64
}

func (q *Queries) UpdateTimeSlot(ctx context.Context, arg UpdateTimeSlotParams) (TimeSlot, error) {
	row := q.db.QueryRowContext(ctx, updateTimeSlot,
		arg.NameKey,
		arg.Icon,
		arg.SortOrder,
		arg.Active,
		arg.ID,
	)
	var i TimeSlot
	err := row.Scan(
		&i.ID,
		&i.NameKey,
		&i.Icon,
		&i.SortOrder,
		&i.Active,
	)
	return i, err
}
