// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: portions.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deletePortion = `-- name: DeletePortion :execresult
DELETE FROM ingredient_portions WHERE ingredient_id = ? AND unit = ?
`

type DeletePortionParams struct {
	IngredientID int64
	Unit         string
}

func (q *Queries) DeletePortion(ctx context.Context, arg DeletePortionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePortion, arg.IngredientID, arg.Unit)
}

const listPortions = `-- name: ListPortions :many
SELECT ingredient_id, unit, grams
FROM ingredient_portions
WHERE ingredient_id = ?
ORDER BY unit
`

func (q *Queries) ListPortions(ctx context.Context, ingredientID int64) ([]IngredientPortion, error) {
	rows, err := q.db.QueryContext(ctx, listPortions, ingredientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngredientPortion{}
	for rows.Next() {
		var i IngredientPortion
		if err := rows.Scan(&i.IngredientID, &i.Unit, &i.Grams); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPortion = `-- name: UpsertPortion :exec
INSERT INTO ingredient_portions (ingredient_id, unit, grams)
VALUES (?, ?, ?)
ON CONFLICT (ingredient_id, unit) DO UPDATE SET grams = excluded.grams
`

type UpsertPortionParams struct {
	IngredientID int64
	Unit         string
	Grams        float64
}

func (q *Queries) UpsertPortion(ctx context.Context, arg UpsertPortionParams) error {
	_, err := q.db.ExecContext(ctx, upsertPortion, arg.IngredientID, arg.Unit, arg.Grams)
	return err
}
