// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: presets.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"strings"
)

const addPresetTag = `-- name: AddPresetTag :exec
INSERT OR IGNORE INTO preset_tags (preset_id, tag) VALUES (?, ?)
`

type AddPresetTagParams struct {
	PresetID int64
	Tag      string
}

func (q *Queries) AddPresetTag(ctx context.Context, arg AddPresetTagParams) error {
	_, err := q.db.ExecContext(ctx, addPresetTag, arg.PresetID, arg.Tag)
	return err
}

const countPresetsUsingFood = `-- name: CountPresetsUsingFood :one
SELECT COUNT(*) FROM preset_components WHERE food_id = ?
`

func (q *Queries) CountPresetsUsingFood(ctx context.Context, foodID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPresetsUsingFood, foodID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPreset = `-- name: CreatePreset :one
INSERT INTO presets (name) VALUES (?) RETURNING id, name, created_at, updated_at, last_used_at
`

func (q *Queries) CreatePreset(ctx context.Context, name string) (Preset, error) {
	row := q.db.QueryRowContext(ctx, createPreset, name)
	var i Preset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createPresetComponent = `-- name: CreatePresetComponent :one
INSERT INTO preset_components (
    preset_plate_id, food_id, portions, amount, unit, grams, grams_source, note, sort_order
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, preset_plate_id, food_id, portions, amount, unit, grams, grams_source, note, sort_order
`

type CreatePresetComponentParams struct {
	PresetPlateID int64
	FoodID        int64
	Portions      sql.NullInt64
	Amount        sql.NullFloat64
	Unit          sql.NullString
	Grams         sql.NullFloat64
	GramsSource   sql.NullString
	Note          sql.NullString
	SortOrder     int64
}

func (q *Queries) CreatePresetComponent(ctx context.Context, arg CreatePresetComponentParams) (PresetComponent, error) {
	row := q.db.QueryRowContext(ctx, createPresetComponent,
		arg.PresetPlateID,
		arg.FoodID,
		arg.Portions,
		arg.Amount,
		arg.Unit,
		arg.Grams,
		arg.GramsSource,
		arg.Note,
		arg.SortOrder,
	)
	var i PresetComponent
	err := row.Scan(
		&i.ID,
		&i.PresetPlateID,
		&i.FoodID,
		&i.Portions,
		&i.Amount,
		&i.Unit,
		&i.Grams,
		&i.GramsSource,
		&i.Note,
		&i.SortOrder,
	)
	return i, err
}

const createPresetPlate = `-- name: CreatePresetPlate :one
INSERT INTO preset_plates (preset_id, slot_id, sort_order) VALUES (?, ?, ?) RETURNING id, preset_id, slot_id, sort_order
`

type CreatePresetPlateParams struct {
	PresetID  int64
	SlotID    int64
	SortOrder int64
}

func (q *Queries) CreatePresetPlate(ctx context.Context, arg CreatePresetPlateParams) (PresetPlate, error) {
	row := q.db.QueryRowContext(ctx, createPresetPlate, arg.PresetID, arg.SlotID, arg.SortOrder)
	var i PresetPlate
	err := row.Scan(
		&i.ID,
		&i.PresetID,
		&i.SlotID,
		&i.SortOrder,
	)
	return i, err
}

const deletePreset = `-- name: DeletePreset :execresult
DELETE FROM presets WHERE id = ?
`

func (q *Queries) DeletePreset(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePreset, id)
}

const deletePresetPlatesByPreset = `-- name: DeletePresetPlatesByPreset :execresult
DELETE FROM preset_plates WHERE preset_id = ?
`

func (q *Queries) DeletePresetPlatesByPreset(ctx context.Context, presetID int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePresetPlatesByPreset, presetID)
}

const deletePresetTag = `-- name: DeletePresetTag :exec
DELETE FROM preset_tags WHERE preset_id = ? AND tag = ?
`

type DeletePresetTagParams struct {
	PresetID int64
	Tag      string
}

func (q *Queries) DeletePresetTag(ctx context.Context, arg DeletePresetTagParams) error {
	_, err := q.db.ExecContext(ctx, deletePresetTag, arg.PresetID, arg.Tag)
	return err
}

const deletePresetTagsByPreset = `-- name: DeletePresetTagsByPreset :exec
DELETE FROM preset_tags WHERE preset_id = ?
`

func (q *Queries) DeletePresetTagsByPreset(ctx context.Context, presetID int64) error {
	_, err := q.db.ExecContext(ctx, deletePresetTagsByPreset, presetID)
	return err
}

const getPreset = `-- name: GetPreset :one
SELECT id, name, created_at, updated_at, last_used_at FROM presets WHERE id = ?
`

func (q *Queries) GetPreset(ctx context.Context, id int64) (Preset, error) {
	row := q.db.QueryRowContext(ctx, getPreset, id)
	var i Preset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listKnownTags = `-- name: ListKnownTags :many
SELECT tag, COUNT(*) AS usage_count
FROM preset_tags
GROUP BY tag
ORDER BY usage_count DESC, tag ASC
LIMIT ?
`

type ListKnownTagsRow struct {
	Tag        string
	UsageCount int64
}

func (q *Queries) ListKnownTags(ctx context.Context, limit int64) ([]ListKnownTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listKnownTags, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKnownTagsRow{}
	for rows.Next() {
		var i ListKnownTagsRow
		if err := rows.Scan(&i.Tag, &i.UsageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresetComponentsByPlate = `-- name: ListPresetComponentsByPlate :many
SELECT id, preset_plate_id, food_id, portions, amount, unit, grams, grams_source, note, sort_order FROM preset_components WHERE preset_plate_id = ? ORDER BY sort_order, id
`

func (q *Queries) ListPresetComponentsByPlate(ctx context.Context, presetPlateID int64) ([]PresetComponent, error) {
	rows, err := q.db.QueryContext(ctx, listPresetComponentsByPlate, presetPlateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PresetComponent{}
	for rows.Next() {
		var i PresetComponent
		if err := rows.Scan(
			&i.ID,
			&i.PresetPlateID,
			&i.FoodID,
			&i.Portions,
			&i.Amount,
			&i.Unit,
			&i.Grams,
			&i.GramsSource,
			&i.Note,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresetComponentsByPreset = `-- name: ListPresetComponentsByPreset :many
SELECT pc.id, pc.preset_plate_id, pc.food_id, pc.portions, pc.amount, pc.unit, pc.grams, pc.grams_source, pc.note, pc.sort_order FROM preset_components pc
JOIN preset_plates pp ON pp.id = pc.preset_plate_id
WHERE pp.preset_id = ?
ORDER BY pp.sort_order, pp.id, pc.sort_order, pc.id
`

func (q *Queries) ListPresetComponentsByPreset(ctx context.Context, presetID int64) ([]PresetComponent, error) {
	rows, err := q.db.QueryContext(ctx, listPresetComponentsByPreset, presetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PresetComponent{}
	for rows.Next() {
		var i PresetComponent
		if err := rows.Scan(
			&i.ID,
			&i.PresetPlateID,
			&i.FoodID,
			&i.Portions,
			&i.Amount,
			&i.Unit,
			&i.Grams,
			&i.GramsSource,
			&i.Note,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresetIDsBySlotID = `-- name: ListPresetIDsBySlotID :many
SELECT DISTINCT preset_id FROM preset_plates WHERE slot_id = ?
`

func (q *Queries) ListPresetIDsBySlotID(ctx context.Context, slotID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listPresetIDsBySlotID, slotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var preset_id int64
		if err := rows.Scan(&preset_id); err != nil {
			return nil, err
		}
		items = append(items, preset_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresetIDsByTag = `-- name: ListPresetIDsByTag :many
SELECT preset_id FROM preset_tags WHERE tag = ?
`

func (q *Queries) ListPresetIDsByTag(ctx context.Context, tag string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listPresetIDsByTag, tag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var preset_id int64
		if err := rows.Scan(&preset_id); err != nil {
			return nil, err
		}
		items = append(items, preset_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresetPlatesByPreset = `-- name: ListPresetPlatesByPreset :many
SELECT id, preset_id, slot_id, sort_order FROM preset_plates WHERE preset_id = ? ORDER BY sort_order, id
`

func (q *Queries) ListPresetPlatesByPreset(ctx context.Context, presetID int64) ([]PresetPlate, error) {
	rows, err := q.db.QueryContext(ctx, listPresetPlatesByPreset, presetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PresetPlate{}
	for rows.Next() {
		var i PresetPlate
		if err := rows.Scan(
			&i.ID,
			&i.PresetID,
			&i.SlotID,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresetTagsByPreset = `-- name: ListPresetTagsByPreset :many
SELECT tag FROM preset_tags WHERE preset_id = ? ORDER BY tag
`

func (q *Queries) ListPresetTagsByPreset(ctx context.Context, presetID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPresetTagsByPreset, presetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresetTagsByPresets = `-- name: ListPresetTagsByPresets :many
SELECT preset_id, tag FROM preset_tags WHERE preset_id IN (/*SLICE:preset_ids*/?)
`

func (q *Queries) ListPresetTagsByPresets(ctx context.Context, presetIds []int64) ([]PresetTag, error) {
	query := listPresetTagsByPresets
	var queryParams []interface{}
	if len(presetIds) > 0 {
		for _, v := range presetIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:preset_ids*/?", strings.Repeat(",?", len(presetIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:preset_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PresetTag{}
	for rows.Next() {
		var i PresetTag
		if err := rows.Scan(&i.PresetID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresets = `-- name: ListPresets :many
SELECT id, name, created_at, updated_at, last_used_at FROM presets ORDER BY name COLLATE NOCASE, id
`

func (q *Queries) ListPresets(ctx context.Context) ([]Preset, error) {
	rows, err := q.db.QueryContext(ctx, listPresets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Preset{}
	for rows.Next() {
		var i Preset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresetsByLastUsed = `-- name: ListPresetsByLastUsed :many
SELECT id, name, created_at, updated_at, last_used_at FROM presets ORDER BY (last_used_at IS NULL), last_used_at DESC, name COLLATE NOCASE, id
`

func (q *Queries) ListPresetsByLastUsed(ctx context.Context) ([]Preset, error) {
	rows, err := q.db.QueryContext(ctx, listPresetsByLastUsed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Preset{}
	for rows.Next() {
		var i Preset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchPresetLastUsedAt = `-- name: TouchPresetLastUsedAt :exec
UPDATE presets SET last_used_at = datetime('now'), updated_at = datetime('now') WHERE id = ?
`

func (q *Queries) TouchPresetLastUsedAt(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchPresetLastUsedAt, id)
	return err
}

const touchPresetUpdatedAt = `-- name: TouchPresetUpdatedAt :exec
UPDATE presets SET updated_at = datetime('now') WHERE id = ?
`

func (q *Queries) TouchPresetUpdatedAt(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchPresetUpdatedAt, id)
	return err
}

const updatePresetName = `-- name: UpdatePresetName :one
UPDATE presets SET name = ?, updated_at = datetime('now') WHERE id = ? RETURNING id, name, created_at, updated_at, last_used_at
`

type UpdatePresetNameParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdatePresetName(ctx context.Context, arg UpdatePresetNameParams) (Preset, error) {
	row := q.db.QueryRowContext(ctx, updatePresetName, arg.Name, arg.ID)
	var i Preset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}
