// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getProfile = `-- name: GetProfile :one
SELECT id, kcal_target, protein_pct, fat_pct, carbs_pct, dietary_restrictions, preferences, system_prompt, locale, updated_at FROM user_profile WHERE id = 1
`

func (q *Queries) GetProfile(ctx context.Context) (UserProfile, error) {
	row := q.db.QueryRowContext(ctx, getProfile)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.KcalTarget,
		&i.ProteinPct,
		&i.FatPct,
		&i.CarbsPct,
		&i.DietaryRestrictions,
		&i.Preferences,
		&i.SystemPrompt,
		&i.Locale,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProfile = `-- name: UpsertProfile :one
UPDATE user_profile
SET kcal_target           = ?,
    protein_pct           = ?,
    fat_pct               = ?,
    carbs_pct             = ?,
    dietary_restrictions  = ?,
    preferences           = ?,
    system_prompt         = ?,
    locale                = ?,
    updated_at            = datetime('now')
WHERE id = 1
RETURNING id, kcal_target, protein_pct, fat_pct, carbs_pct, dietary_restrictions, preferences, system_prompt, locale, updated_at
`

type UpsertProfileParams struct {
	KcalTarget          sql.NullFloat64
	ProteinPct          sql.NullFloat64
	FatPct              sql.NullFloat64
	CarbsPct            sql.NullFloat64
	DietaryRestrictions string
	Preferences         string
	SystemPrompt        sql.NullString
	Locale              string
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) (UserProfile, error) {
	row := q.db.QueryRowContext(ctx, upsertProfile,
		arg.KcalTarget,
		arg.ProteinPct,
		arg.FatPct,
		arg.CarbsPct,
		arg.DietaryRestrictions,
		arg.Preferences,
		arg.SystemPrompt,
		arg.Locale,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.KcalTarget,
		&i.ProteinPct,
		&i.FatPct,
		&i.CarbsPct,
		&i.DietaryRestrictions,
		&i.Preferences,
		&i.SystemPrompt,
		&i.Locale,
		&i.UpdatedAt,
	)
	return i, err
}
