// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddPresetTag(ctx context.Context, arg AddPresetTagParams) error
	AppendMessage(ctx context.Context, arg AppendMessageParams) (AiMessage, error)
	CountConversations(ctx context.Context) (int64, error)
	CountConversationsByWeek(ctx context.Context, weekID sql.NullInt64) (int64, error)
	CountPlatesUsingFood(ctx context.Context, foodID int64) (int64, error)
	CountPlatesUsingTimeSlot(ctx context.Context, slotID int64) (int64, error)
	CountPresetsUsingFood(ctx context.Context, foodID int64) (int64, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (AiConversation, error)
	CreateFood(ctx context.Context, arg CreateFoodParams) (Food, error)
	CreateFoodComponent(ctx context.Context, arg CreateFoodComponentParams) error
	CreateFoodInstruction(ctx context.Context, arg CreateFoodInstructionParams) error
	CreateFoodTag(ctx context.Context, arg CreateFoodTagParams) error
	CreatePlate(ctx context.Context, arg CreatePlateParams) (Plate, error)
	CreatePlateComponent(ctx context.Context, arg CreatePlateComponentParams) (PlateComponent, error)
	CreatePreset(ctx context.Context, name string) (Preset, error)
	CreatePresetComponent(ctx context.Context, arg CreatePresetComponentParams) (PresetComponent, error)
	CreatePresetPlate(ctx context.Context, arg CreatePresetPlateParams) (PresetPlate, error)
	CreateTimeSlot(ctx context.Context, arg CreateTimeSlotParams) (TimeSlot, error)
	CreateVariantGroup(ctx context.Context, name string) (VariantGroup, error)
	DeleteConversation(ctx context.Context, id int64) (sql.Result, error)
	DeleteFood(ctx context.Context, id int64) (sql.Result, error)
	DeleteFoodComponents(ctx context.Context, parentID int64) error
	DeleteFoodInstructions(ctx context.Context, foodID int64) error
	DeleteFoodPortion(ctx context.Context, arg DeleteFoodPortionParams) (sql.Result, error)
	DeleteFoodTags(ctx context.Context, foodID int64) error
	DeletePlate(ctx context.Context, id int64) (sql.Result, error)
	DeletePlateComponent(ctx context.Context, id int64) (sql.Result, error)
	DeletePlateFeedback(ctx context.Context, plateID int64) (sql.Result, error)
	DeletePreset(ctx context.Context, id int64) (sql.Result, error)
	DeletePresetPlatesByPreset(ctx context.Context, presetID int64) (sql.Result, error)
	DeletePresetTag(ctx context.Context, arg DeletePresetTagParams) error
	DeletePresetTagsByPreset(ctx context.Context, presetID int64) error
	DeleteSetting(ctx context.Context, key string) error
	DeleteTimeSlot(ctx context.Context, id int64) (sql.Result, error)
	GetConversation(ctx context.Context, id int64) (AiConversation, error)
	GetFood(ctx context.Context, id int64) (Food, error)
	GetFoodKind(ctx context.Context, id int64) (string, error)
	GetPlate(ctx context.Context, id int64) (Plate, error)
	GetPlateComponent(ctx context.Context, id int64) (PlateComponent, error)
	GetPlateFeedback(ctx context.Context, plateID int64) (PlateFeedback, error)
	GetPreset(ctx context.Context, id int64) (Preset, error)
	GetProfile(ctx context.Context) (UserProfile, error)
	GetSetting(ctx context.Context, key string) (AppSetting, error)
	GetTimeSlot(ctx context.Context, id int64) (TimeSlot, error)
	ListActiveTimeSlots(ctx context.Context) ([]TimeSlot, error)
	ListConversations(ctx context.Context, arg ListConversationsParams) ([]AiConversation, error)
	ListConversationsByWeek(ctx context.Context, arg ListConversationsByWeekParams) ([]AiConversation, error)
	ListFoodComponents(ctx context.Context, parentID int64) ([]ListFoodComponentsRow, error)
	ListFoodInstructions(ctx context.Context, foodID int64) ([]FoodInstruction, error)
	ListFoodPortions(ctx context.Context, foodID int64) ([]FoodPortion, error)
	ListFoodTags(ctx context.Context, foodID int64) ([]FoodTag, error)
	ListForgottenFoods(ctx context.Context, arg ListForgottenFoodsParams) ([]Food, error)
	ListKnownTags(ctx context.Context, limit int64) ([]ListKnownTagsRow, error)
	ListMessages(ctx context.Context, conversationID int64) ([]AiMessage, error)
	ListMostCookedFoods(ctx context.Context, limit int64) ([]Food, error)
	ListPlateComponentsByPlate(ctx context.Context, plateID int64) ([]PlateComponent, error)
	ListPlatesByDate(ctx context.Context, date string) ([]Plate, error)
	ListPlatesByDateRange(ctx context.Context, arg ListPlatesByDateRangeParams) ([]Plate, error)
	ListPresetComponentsByPlate(ctx context.Context, presetPlateID int64) ([]PresetComponent, error)
	ListPresetComponentsByPreset(ctx context.Context, presetID int64) ([]PresetComponent, error)
	ListPresetIDsBySlotID(ctx context.Context, slotID int64) ([]int64, error)
	ListPresetIDsByTag(ctx context.Context, tag string) ([]int64, error)
	ListPresetPlatesByPreset(ctx context.Context, presetID int64) ([]PresetPlate, error)
	ListPresetTagsByPreset(ctx context.Context, presetID int64) ([]string, error)
	ListPresetTagsByPresets(ctx context.Context, presetIds []int64) ([]PresetTag, error)
	ListPresets(ctx context.Context) ([]Preset, error)
	ListPresetsByLastUsed(ctx context.Context) ([]Preset, error)
	ListSettings(ctx context.Context) ([]AppSetting, error)
	ListSiblingFoods(ctx context.Context, arg ListSiblingFoodsParams) ([]Food, error)
	ListTimeSlots(ctx context.Context) ([]TimeSlot, error)
	MarkFoodCooked(ctx context.Context, arg MarkFoodCookedParams) error
	RecentUnitForFood(ctx context.Context, foodID int64) (sql.NullString, error)
	// Placeholder query so sqlc has something to generate in Phase 0. Real
	// aggregate queries replace this starting in Phase 1 (ingredients).
	SchemaVersion(ctx context.Context) (int64, error)
	SetFoodFavorite(ctx context.Context, arg SetFoodFavoriteParams) (Food, error)
	SetPlateSkipped(ctx context.Context, arg SetPlateSkippedParams) (Plate, error)
	TouchConversation(ctx context.Context, id int64) (sql.Result, error)
	TouchPresetLastUsedAt(ctx context.Context, id int64) error
	TouchPresetUpdatedAt(ctx context.Context, id int64) error
	UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) (AiConversation, error)
	UpdateFood(ctx context.Context, arg UpdateFoodParams) (Food, error)
	UpdatePlate(ctx context.Context, arg UpdatePlateParams) (Plate, error)
	UpdatePlateComponent(ctx context.Context, arg UpdatePlateComponentParams) (PlateComponent, error)
	UpdatePresetName(ctx context.Context, arg UpdatePresetNameParams) (Preset, error)
	UpdateTimeSlot(ctx context.Context, arg UpdateTimeSlotParams) (TimeSlot, error)
	UpsertFoodPortion(ctx context.Context, arg UpsertFoodPortionParams) error
	UpsertPlateFeedback(ctx context.Context, arg UpsertPlateFeedbackParams) (PlateFeedback, error)
	UpsertProfile(ctx context.Context, arg UpsertProfileParams) (UserProfile, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
}

var _ Querier = (*Queries)(nil)
