// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountPlatesUsingComponent(ctx context.Context, componentID int64) (int64, error)
	CountPlatesUsingTimeSlot(ctx context.Context, slotID int64) (int64, error)
	CountWeeks(ctx context.Context) (int64, error)
	CreateComponent(ctx context.Context, arg CreateComponentParams) (Component, error)
	CreateComponentIngredient(ctx context.Context, arg CreateComponentIngredientParams) error
	CreateComponentInstruction(ctx context.Context, arg CreateComponentInstructionParams) error
	CreateComponentTag(ctx context.Context, arg CreateComponentTagParams) error
	CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error)
	CreatePlate(ctx context.Context, arg CreatePlateParams) (Plate, error)
	CreatePlateComponent(ctx context.Context, arg CreatePlateComponentParams) (PlateComponent, error)
	CreateTimeSlot(ctx context.Context, arg CreateTimeSlotParams) (TimeSlot, error)
	CreateVariantGroup(ctx context.Context, name string) (VariantGroup, error)
	CreateWeek(ctx context.Context, arg CreateWeekParams) (Week, error)
	DeleteComponent(ctx context.Context, id int64) (sql.Result, error)
	DeleteComponentIngredients(ctx context.Context, componentID int64) error
	DeleteComponentInstructions(ctx context.Context, componentID int64) error
	DeleteComponentTags(ctx context.Context, componentID int64) error
	DeleteIngredient(ctx context.Context, id int64) (sql.Result, error)
	DeletePlate(ctx context.Context, id int64) (sql.Result, error)
	DeletePlateComponent(ctx context.Context, id int64) (sql.Result, error)
	DeletePortion(ctx context.Context, arg DeletePortionParams) (sql.Result, error)
	DeleteTimeSlot(ctx context.Context, id int64) (sql.Result, error)
	GetComponent(ctx context.Context, id int64) (Component, error)
	GetIngredient(ctx context.Context, id int64) (Ingredient, error)
	GetPlate(ctx context.Context, id int64) (Plate, error)
	GetPlateComponent(ctx context.Context, id int64) (PlateComponent, error)
	GetTimeSlot(ctx context.Context, id int64) (TimeSlot, error)
	GetWeek(ctx context.Context, id int64) (Week, error)
	GetWeekByYearAndNumber(ctx context.Context, arg GetWeekByYearAndNumberParams) (Week, error)
	ListActiveTimeSlots(ctx context.Context) ([]TimeSlot, error)
	ListComponentIngredients(ctx context.Context, componentID int64) ([]ComponentIngredient, error)
	ListComponentInstructions(ctx context.Context, componentID int64) ([]ComponentInstruction, error)
	ListComponentTags(ctx context.Context, componentID int64) ([]ComponentTag, error)
	ListPlateComponentsByPlate(ctx context.Context, plateID int64) ([]PlateComponent, error)
	ListPlateComponentsByWeek(ctx context.Context, weekID int64) ([]PlateComponent, error)
	ListPlatesByWeek(ctx context.Context, weekID int64) ([]Plate, error)
	ListPortions(ctx context.Context, ingredientID int64) ([]IngredientPortion, error)
	ListSiblingComponents(ctx context.Context, arg ListSiblingComponentsParams) ([]Component, error)
	ListTimeSlots(ctx context.Context) ([]TimeSlot, error)
	ListWeeks(ctx context.Context, arg ListWeeksParams) ([]Week, error)
	// Placeholder query so sqlc has something to generate in Phase 0. Real
	// aggregate queries replace this starting in Phase 1 (ingredients).
	SchemaVersion(ctx context.Context) (int64, error)
	UpdateComponent(ctx context.Context, arg UpdateComponentParams) (Component, error)
	UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) (Ingredient, error)
	UpdatePlate(ctx context.Context, arg UpdatePlateParams) (Plate, error)
	UpdatePlateComponent(ctx context.Context, arg UpdatePlateComponentParams) (PlateComponent, error)
	UpdateTimeSlot(ctx context.Context, arg UpdateTimeSlotParams) (TimeSlot, error)
	UpsertPortion(ctx context.Context, arg UpsertPortionParams) error
}

var _ Querier = (*Queries)(nil)
