// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countTemplatesUsingFood = `-- name: CountTemplatesUsingFood :one
SELECT COUNT(*) FROM template_entries WHERE food_id = ?
`

func (q *Queries) CountTemplatesUsingFood(ctx context.Context, foodID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTemplatesUsingFood, foodID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (name, scope) VALUES (?, ?) RETURNING id, name, created_at, scope
`

type CreateTemplateParams struct {
	Name  string
	Scope string
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, createTemplate, arg.Name, arg.Scope)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Scope,
	)
	return i, err
}

const createTemplateEntry = `-- name: CreateTemplateEntry :one
INSERT INTO template_entries (template_id, food_id, portions, sort_order, day_offset, slot_id, note)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, template_id, food_id, portions, sort_order, day_offset, slot_id, note
`

type CreateTemplateEntryParams struct {
	TemplateID int64
	FoodID     int64
	Portions   float64
	SortOrder  int64
	DayOffset  int64
	SlotID     sql.NullInt64
	Note       sql.NullString
}

func (q *Queries) CreateTemplateEntry(ctx context.Context, arg CreateTemplateEntryParams) (TemplateEntry, error) {
	row := q.db.QueryRowContext(ctx, createTemplateEntry,
		arg.TemplateID,
		arg.FoodID,
		arg.Portions,
		arg.SortOrder,
		arg.DayOffset,
		arg.SlotID,
		arg.Note,
	)
	var i TemplateEntry
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.FoodID,
		&i.Portions,
		&i.SortOrder,
		&i.DayOffset,
		&i.SlotID,
		&i.Note,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :execresult
DELETE FROM templates WHERE id = ?
`

func (q *Queries) DeleteTemplate(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTemplate, id)
}

const deleteTemplateEntriesByTemplate = `-- name: DeleteTemplateEntriesByTemplate :execresult
DELETE FROM template_entries WHERE template_id = ?
`

func (q *Queries) DeleteTemplateEntriesByTemplate(ctx context.Context, templateID int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTemplateEntriesByTemplate, templateID)
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, name, created_at, scope FROM templates WHERE id = ?
`

func (q *Queries) GetTemplate(ctx context.Context, id int64) (Template, error) {
	row := q.db.QueryRowContext(ctx, getTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Scope,
	)
	return i, err
}

const listTemplateEntriesByTemplate = `-- name: ListTemplateEntriesByTemplate :many
SELECT id, template_id, food_id, portions, sort_order, day_offset, slot_id, note FROM template_entries WHERE template_id = ? ORDER BY sort_order, id
`

func (q *Queries) ListTemplateEntriesByTemplate(ctx context.Context, templateID int64) ([]TemplateEntry, error) {
	rows, err := q.db.QueryContext(ctx, listTemplateEntriesByTemplate, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemplateEntry{}
	for rows.Next() {
		var i TemplateEntry
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.FoodID,
			&i.Portions,
			&i.SortOrder,
			&i.DayOffset,
			&i.SlotID,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, name, created_at, scope FROM templates ORDER BY name, id
`

func (q *Queries) ListTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesByScope = `-- name: ListTemplatesByScope :many
SELECT id, name, created_at, scope FROM templates WHERE scope = ? ORDER BY name, id
`

func (q *Queries) ListTemplatesByScope(ctx context.Context, scope string) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, listTemplatesByScope, scope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplateName = `-- name: UpdateTemplateName :one
UPDATE templates SET name = ? WHERE id = ? RETURNING id, name, created_at, scope
`

type UpdateTemplateNameParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateTemplateName(ctx context.Context, arg UpdateTemplateNameParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, updateTemplateName, arg.Name, arg.ID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Scope,
	)
	return i, err
}
