// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countTemplatesUsingFood = `-- name: CountTemplatesUsingFood :one
SELECT COUNT(*) FROM template_components WHERE food_id = ?
`

func (q *Queries) CountTemplatesUsingFood(ctx context.Context, foodID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTemplatesUsingFood, foodID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (name) VALUES (?) RETURNING id, name, created_at
`

func (q *Queries) CreateTemplate(ctx context.Context, name string) (Template, error) {
	row := q.db.QueryRowContext(ctx, createTemplate, name)
	var i Template
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createTemplateComponent = `-- name: CreateTemplateComponent :one
INSERT INTO template_components (template_id, food_id, portions, sort_order)
VALUES (?, ?, ?, ?)
RETURNING id, template_id, food_id, portions, sort_order
`

type CreateTemplateComponentParams struct {
	TemplateID int64
	FoodID     int64
	Portions   float64
	SortOrder  int64
}

func (q *Queries) CreateTemplateComponent(ctx context.Context, arg CreateTemplateComponentParams) (TemplateComponent, error) {
	row := q.db.QueryRowContext(ctx, createTemplateComponent,
		arg.TemplateID,
		arg.FoodID,
		arg.Portions,
		arg.SortOrder,
	)
	var i TemplateComponent
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.FoodID,
		&i.Portions,
		&i.SortOrder,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :execresult
DELETE FROM templates WHERE id = ?
`

func (q *Queries) DeleteTemplate(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTemplate, id)
}

const deleteTemplateComponentsByTemplate = `-- name: DeleteTemplateComponentsByTemplate :execresult
DELETE FROM template_components WHERE template_id = ?
`

func (q *Queries) DeleteTemplateComponentsByTemplate(ctx context.Context, templateID int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTemplateComponentsByTemplate, templateID)
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, name, created_at FROM templates WHERE id = ?
`

func (q *Queries) GetTemplate(ctx context.Context, id int64) (Template, error) {
	row := q.db.QueryRowContext(ctx, getTemplate, id)
	var i Template
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listTemplateComponentsByTemplate = `-- name: ListTemplateComponentsByTemplate :many
SELECT id, template_id, food_id, portions, sort_order FROM template_components WHERE template_id = ? ORDER BY sort_order, id
`

func (q *Queries) ListTemplateComponentsByTemplate(ctx context.Context, templateID int64) ([]TemplateComponent, error) {
	rows, err := q.db.QueryContext(ctx, listTemplateComponentsByTemplate, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemplateComponent{}
	for rows.Next() {
		var i TemplateComponent
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.FoodID,
			&i.Portions,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, name, created_at FROM templates ORDER BY name, id
`

func (q *Queries) ListTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplateName = `-- name: UpdateTemplateName :one
UPDATE templates SET name = ? WHERE id = ? RETURNING id, name, created_at
`

type UpdateTemplateNameParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateTemplateName(ctx context.Context, arg UpdateTemplateNameParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, updateTemplateName, arg.Name, arg.ID)
	var i Template
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
